### ISSUE TITLE
How to enable Azure AD SSO for the customer sign-up portal?

### ISSUE THREAD

**Issue by lostmsu** [Azure/Commercial-Marketplace-SaaS-Accelerator#104]
**Is your feature request related to a problem? Please describe.**
I published a SaaS solution to the Marketplace, however my customers can't sign in into `https://xxxx-portal.azurewebsites.net/` after subscribing in Azure Portal. Clicking "Configure account now" sends them to the page where they can pick an Azure-bound email, but clicking on that account simply loads the same page again.

![image](https://user-images.githubusercontent.com/239520/91783327-b5811e00-ebb4-11ea-91a3-1759a416000a.png)

The same effect has going directly to  `https://xxxx-portal.azurewebsites.net/` and clicking "Sign-in" in the top right.

At one moment I received an email from Partner Center, mentioning the possible cause:

> We reviewed your offer and found that landing page does not support Azure Active Directory (Azure AD) single sign-on (SSO) or your Azure AD SSO is mis-configured. Marketplace buyers are authenticated with Azure AD before they can buy your software as a service (SaaS) offer. To avoid abandonment and facilitate activation, you must enable Azure AD SSO for the buyer of your transactable SaaS offer. To comply with these commercial marketplace certification policies, build or update the offer landing page with Azure AD SSO support. Learn more: https://docs.microsoft.com/en-us/azure/marketplace/azure-ad-transactable-saas-landing-page

However, I am not sure how to configure Azure AD SSO correctly.

Currently, it seems that only I can sign in into the portal.

**Describe the solution you'd like**
I need my customers to be able to enter the portal and view their subscriptions.

**Comment by lostmsu** [comment]
OK, I found
![image](https://user-images.githubusercontent.com/239520/91784058-c03cb280-ebb6-11ea-9ee7-bf620323e397.png)
This was set to the first option. Changing this to the "Multitenant" option now get the following error message:

> Selected user account does not exist in tenant 'My Tenant' and cannot access the application '41cdff0b-aeac-413d-a4b3-53de04a7e1ab' in that tenant. The account needs to be added as an external user in the tenant first. Please use a different account.

**Comment by lostmsu** [comment]
This seems to be related to 2. in the documentation here: https://docs.microsoft.com/en-us/azure/marketplace/azure-ad-saas#process-steps-for-purchase-management

How do I make portal web site to accept any Azure AD/MSA identity, not only ones in my own AD?

**Comment by alexdrenea** [comment]
I know this is an old issue but wanted to post the resolution to this for future reference.

The current version of the accelerator will generate a proper Application Registration that allows for personal account authentication as well, however if you registered the app before or have not used the accelerator here's the way to update it:

In the App Registration in Azure, navigate to the Manifest section, and update the follwowing:

FROM:
`"signInAudience": "AzureADMultipleOrgs",`

TO:
`"signInAudience": "AzureADandPersonalMicrosoftAccount",`

**Comment by alexdrenea** [comment]
@code4clouds - I think it's safe to close this issue now.

**Comment by santhoshb-msft** [comment]
Thanks @alexdrenea !

@lostmsu - closing this for now, please reopen if needed
