### ISSUE TITLE
UsersRepository.Save() fails to call SaveChanges() for an existing user

### ISSUE THREAD

**Issue by Dmitry-Me** [Azure/Commercial-Marketplace-SaaS-Accelerator#105]
UsersRepository.Save() currently goes like this:

            if (existingUser != null)
            {
                existingUser.FullName = userDetail.FullName;
                this.context.Users.Update(existingUser);
                return existingUser.UserId;
            }
            else
            {
                this.context.Users.Add(userDetail);
            }

            this.context.SaveChanges();
            return userDetail.UserId;

`SaveChanges` is only called after `Add()` branch is executed. `SaveChanges()` is not called if control passes through `Update()` branch.

**Comment by santhoshb-msft** [comment]
Discussed with @v-ade .
WE are still trying to see if the save is any relevant for the existing user.

**Comment by v-ade** [comment]
No change required.

**Comment by santhoshb-msft** [comment]
Hi @v-ade as discussed can you please add some reasoning.

**Comment by santhoshb-msft** [comment]
@v-ade any update on the reasoning here please?

**Comment by v-adeadepoju** [comment]
> No change required.

No change required. I could not determine this was a bug and feature works as expected.

**Comment by santhoshb-msft** [comment]
Thank @v-adeadepoju closing this as per comments
