### ISSUE TITLE
Installation Instructions: Create Web Apps on Azure and deploy the code Link Text for Publisher sample web application

### ISSUE THREAD

**Issue by MichaelSchreiber** [Azure/Commercial-Marketplace-SaaS-Accelerator#109]
**Describe the bug**
In chapter "Create Web Apps on Azure and deploy the code" of the installation instructrions, the text for the link to source for the "Publisher sample web application" is wrong. It says "src/SaaS.SDK.CustomerProvisioning" but correctly targets the publisher solution.

**To Reproduce**
1. Go to [https://github.com/Azure/Microsoft-commercial-marketplace-transactable-SaaS-offer-SDK/blob/master/docs/Installation-Instructions.md#create-web-apps-on-azure-and-deploy-the-code]
2. See error: The text for both links is the same, though the target is different.

**Expected behavior**
The text should correspond to the target of the link.
![image](https://user-images.githubusercontent.com/22149486/95647284-81135280-0ace-11eb-8cd4-ef72f7ea3f92.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Edge Chrome
 - Version current

**Comment by alexdrenea** [comment]
Page has changed in the meantime, this issue is no longer valid. Recommend closing @code4clouds
