### ISSUE TITLE
Update to new C# Client Library

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#112]
**Is your feature request related to a problem? Please describe.**
A new feature request.  There is a new .NET client Library

**Describe the solution you'd like**
It uses the new NuGet library, instead of the custom-built library

**Describe alternatives you've considered**
None, there is an official library and that should be used.

**Additional context**

**Comment by alexdrenea** [comment]
I think this is done and can be closed @code4clouds

**Comment by code4clouds** [comment]
Yes... Thanks!  Closing.
