### ISSUE TITLE
Add License Management for Per Seat Base Offers

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#130]
**Is your feature request related to a problem? Please describe. **
The Accelerator supports seats offers, but not the management of them.   It would be nice if it covers this.

**Describe the solution you'd like**

Implement licensing management
Your service (website) must allow the admin who has made the purchase to sign in and manage the account. In the case where they have bought multiple seat-based licenses, they should be able to assign these to users within their organization. You might want to consider the following types of licensing:

Open licensing/first-come first-served - Any end-user who discovers your service can sign in to your service, be recognized as belonging to a tenant, and reserve one of the licenses purchased.
Assigned licensing - The admin for the purchase must assign licenses to users.
Other considerations:

Upsell - If a user tries to access your service, but their tenant has no more free licenses, you service could provide them with a temporary license, and use the opportunity to encourage the admin to purchase additional licenses.
Multiple tenant purchases - You should consider whether to allow numerous purchases from the same tenant, and how to treat these in your database. For example, the Contoso Corporation sales team might purchase 50 licenses for their team, and the marketing team purchase 20 licenses for their team, and they might want to keep the account separate.

https://docs.microsoft.com/en-us/office/dev/store/monetize-addins-through-microsoft-commercial-marketplace#implement-licensing-management

**Additional context**

**Comment by MichaelSchreiber** [comment]
Feature request: I also need a way to assign licenses to users for per-seat based offers.

**Comment by santhoshb-msft** [comment]
I see a couple of challenges. 
1. It makes the whole app a little complex
2. I think we are getting into specifics than keeping it generic.
Still a good feature to have.

**Comment by santhoshb-msft** [comment]
Thanks for the explanation/feedback, @MichaelSchreiber !

Sure @dstarr , lets sync up.

**Comment by MichaelSchreiber** [comment]
@dstarr & @santhoshb-msft Thanks! Great to see that the topic gets attention.
If it is of value for any of you, I'll be glad to describe my requirements - of which I think that they are fairly general - and provide a description on how I plan to solve it in the application.

**Comment by LokeshKanumoori** [comment]
Any Update on this?

**Comment by dstarr** [comment]
As the licensing landscape for products matures, we will take a wait and see approach to how per-user licensing works across all relevant offers. At the moment, the Turnstile project offers a good solution for license management outside of the accelerator and taking a dependency on this one solution would tie us to it, thus not a great option for long-term.

Today, solution providers manage their own licensing services, which are the appropriate places to surface this kind of licensing information. This is a no-op for the time being.
