### ISSUE TITLE
Allow new code updates without having to delete the db

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#136]
**Is your feature request related to a problem? Please describe.**
As an IT administrator.,
I would like to update to the new code of the Accelerator
without having to delete the DB.

**Describe the solution you'd like**
If the script is re-run as the user if the db should be preserved (or even skipped) during an update

**Describe alternatives you've considered**

**Additional context**

**Comment by santhoshb-msft** [comment]
Given the EF migrations is now merged into main, this should be now be possible.
@code4clouds please let me know if this still needs anything else to be addressed. Closing this for now.
