### ISSUE TITLE
Duplicate dimensions created

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/Commercial-Marketplace-SaaS-Accelerator#152]
Duplicate dimensions entries are created

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by alexdrenea** [comment]
The problem appears when users use the Azure portal to navigate to the Landing Page once an offer has been activated.
This triggers the Landing Page logic which in turn calls ```this.subscriptionService.AddPlanDetailsForSubscription(subscriptionPlanDetail);``` [Line 222](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/a3810acb949250aec554cde29c9f89048cab3e13/src/SaaS.SDK.CustomerProvisioning/Controllers/HomeController.cs#L222)

During this call, the execution logic eventually reaches the `PlansRepository.Save()` method. In here, when loading the existing plan we are lot also loading the Metered Dimensions associated and then in [line 80](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/a3810acb949250aec554cde29c9f89048cab3e13/src/SaaS.SDK.Client.DataAccess/Services/PlansRepository.cs#L80) the MeteredDimensions property gets reassigned to the new collection that contains same items again.

The solution is two fold: 1. Load the MeteredDimensions property when reading existingPlans from the Database. 2. Only add dimensions that are potentially new from planDetails.

**Comment by santhoshb-msft** [comment]
Once a plan with dimensions are published there is no adding of add additional/update dimensions is allowed in partner center. Which means we can take out the line about that dimension on plan update. I will make the change, we can test it.
