### ISSUE TITLE
Upgrade to .NET 6?

### ISSUE THREAD

**Issue by alexdrenea** [Azure/Commercial-Marketplace-SaaS-Accelerator#158]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Should the solution upgrade to .NET 6 ?

**Comment by pbutlerm** [comment]
Hi @lexdrenea, 

Thanks for your feedback. Let me review with the team. We want to snap to .NET Core Long Term support releases for this project, since it is deployed in multiple OSes.

**Comment by dstarr** [comment]
> Hi @alexdrenea,
> 
> Thanks for your feedback. Let me review with the team. We want to snap to .NET Core Long Term support releases for this project, since it is deployed on multiple OSes.

.NET 6 is [LTS](https://github.com/dotnet/core/blob/main/releases.md).

**Comment by alexdrenea** [comment]
@dstarr @pbutlerm following up on this...
Any interest in upgrading the solution to .NET 6 LTS? 
I have done a test locally and it seems pretty straight forward. I can have a PR up relatively quickly

**Comment by dstarr** [comment]
There is definitely from me. We have several outstanding PRs. Let me talk to the team about which to take and in what order, and then we can look at doing an upgrade.

**Comment by alexdrenea** [comment]
Awesome! When you are ready, let me know, I already have a branch that I set up for my own local development (Hot reload is awesome) and I can just PR that

**Comment by muzzar78** [comment]
I'd love to see this project upgraded to .NET 6 LTS. We are about to start building out our marketplace offering and if you would like someone to test the solution with .NET 6 I'd be happy to do that. @alexdrenea If you are happy to push your branch I can build our solution of that and see if I hit any issues.

**Comment by alexdrenea** [comment]
@muzzar78 PR is up #187 

You can also just clone the branch from my fork if you want to test (https://github.com/alexdrenea/Commercial-Marketplace-SaaS-Accelerator/tree/feature/net6-lts)

**Comment by muzzar78** [comment]
@alexdrenea Thanks for the quick response. I have cloned your repo and I'll let you know if we run into any issues.

**Comment by muzzar78** [comment]
@alexdrenea I had an issue with authentication with .NET 6 that looks like it is related to the way the claims are coming through. Other than that it seems to be working as expected.

I updated ClaimConstants.cs with the following values to get it to work.

```
public class ClaimConstants
    {
        /// <summary>
        /// Defines the CLAIM_EMAILADDRESS.
        /// </summary>
        public const string CLAIM_EMAILADDRESS = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn";

        /// <summary>
        /// The claim name.
        /// </summary>
        public const string CLAIM_NAME = "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name";
    }
```

**Comment by alexdrenea** [comment]
Thanks @muzzar78 ! This was super helpful!
Just got another report that we are using the older OAuth endpoint (v1) and that causes to us to be unable to login with Personal Accounts. Changing that to v2, also changes the claims and needed to update them again.

Will make the changes and push an update to the branch today!

**Comment by alexdrenea** [comment]
@muzzar78 -> Fixed the issue. Branch is pushed on the fork so you can try it out! Thanks again for the feedback

**Comment by muzzar78** [comment]
Hi @alexdrenea I have tried the update but I'm getting the following error during sign in - SecurityTokenInvalidIssuerException: IDX10205. I enabled IdentityModelEventSource.ShowPII = true; to get more info. I have replace my actual tenant id below with 'my tenant id'.

SecurityTokenInvalidIssuerException: IDX10205: Issuer validation failed. Issuer: 'https://login.microsoftonline.com/my tenant id/v2.0'. Did not match: validationParameters.ValidIssuer: 'null' or validationParameters.ValidIssuers: 'https://login.microsoftonline.com/{tenantid}/v2.0'.

**Comment by alexdrenea** [comment]
Yes, sorry about that, I had missed that piece in the original commit. I put a fix in the next day and that should fix the issue (https://github.com/alexdrenea/Commercial-Marketplace-SaaS-Accelerator/commit/f4d8ef934d3373939e28432342b6f68c2159d45b)

**Comment by alexdrenea** [comment]
@muzzar78 following up to see if you got a chance to check the version with the fix! Thanks!

**Comment by muzzar78** [comment]
Hi @alexdrenea, Yes I did test the updated version and it is working and everything looks good. Thanks. I did notice the unsubscribe webhook is failing but I see there is already a [PR](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/pull/182) to fix it.

**Comment by code4clouds** [comment]
.NET 6.0 is now in master.
