### ISSUE TITLE
to which id does mtclientid maps

### ISSUE THREAD

**Issue by cdhemant** [Azure/Commercial-Marketplace-SaaS-Accelerator#164]
There is setting **mtclientid** not sure to which id it must be mapped?
does it needs to be objectid of the registered app?

Thanks
Hemant

**Comment by santhoshb-msft** [comment]
This will be the applicationId/clientId of the app registration which you would like to use for the login user authentication on the app.

**Comment by cdhemant** [comment]
Thank you @santhoshb-msft
