### ISSUE TITLE
PostUsage event returns status as null

### ISSUE THREAD

**Issue by cdhemant** [Azure/Commercial-Marketplace-SaaS-Accelerator#166]
Hello,

My Azure managed application is in preview mode . So does it mean PostUsageEventAsync event will be successful but response will be null ??
{
		"status": null,
		"effectiveStartTime": null,
		"usageEventId": "00000000-0000-0000-0000-000000000000",
		"messageTime": "0001-01-01T00:00:00",
		"resourceId": "00000000-0000-0000-0000-000000000000",
		"quantity": 0,
		"dimension": null,
		"planId": null,
		"RequestID": null
}

Thanks
Hemant

**Comment by alexdrenea** [comment]
This looks to be a bug in the code. 
I will provide a PR for the fix in a bit! 
Thank you for reporting the issue
