### ISSUE TITLE
Azure SQL firewall deployment problem - security vulnerability

### ISSUE THREAD

**Issue by alexdrenea** [Azure/Commercial-Marketplace-SaaS-Accelerator#170]
The SQL database is being deployed with a firewall rule that allows ALL IPs to connect to the database thus rendering the default SQL firewall useless.

[deploy.json line 120-121](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/a3810acb949250aec554cde29c9f89048cab3e13/deployment/Templates/deploy.json#L120-L121)

```
        "startIpAddress": "0.0.0.0",
        "endIpAddress": "255.255.255.255"
```

If the intent was to allow Azure IPs access to the SQL database, endIpAddress should also be "0.0.0.0" [docs](https://docs.microsoft.com/en-us/azure/templates/microsoft.sql/servers/firewallrules?tabs=bicep#serverfirewallruleproperties)

**Comment by santhoshb-msft** [comment]
Thanks @alexdrenea , this is fixed PR #244
