### ISSUE TITLE
ClientSecretCredential

### ISSUE THREAD

**Issue by bassamalasadi** [Azure/Commercial-Marketplace-SaaS-Accelerator#174]
The access to the landing and admin page is working properly. but when a customer tries to configure his subscription on the landing page he gets this error. What is the cause of this error?

![image](https://i.ibb.co/JsWgT7M/22.jpg)

**Comment by santhoshb-msft** [comment]
Hi @bassamalasadi This most likely means the single tenant app reg secret is not set in the appsettings.

**Comment by santhoshb-msft** [comment]
Hi @bassamalasadi This most likely means the single tenant app reg secret is not set in the appsettings.

**Comment by bassamalasadi** [comment]
Thank you @santhoshb-msft

**Comment by Githamza** [comment]
I'm getting the same issue , but I'm new to saas accelertor , can you explain me steps to take exactly ?
there is many appsettings files.
How to redeploy the saas accelerator with the right secret ?

Error 500 : ClientSecretCredential authentication failed: A configuration issue is preventing authentication - check the error message from the server for details.You can modify the configuration in the application registration portal. See https://aka.ms/msal-net-invalid-client for details. Original exception: AADSTS7000215: Invalid client secret provided. Ensure the secret being sent in the request is the client secret value, not the client secret ID, for a secret added to app '150ad515-7985-45b3-900a-fec1626e06d3'. Trace ID: 6395b8c2-897a-4ea0-a713-c97501ef7100 Correlation ID: 474c5797-76fb-4749-b45f-8d9dbae0ce66 Timestamp: 2023-11-17 19:42:04Z
