### ISSUE TITLE
ClientSecretCredential authentication failing

### ISSUE THREAD

**Issue by selwynoh** [Azure/Commercial-Marketplace-SaaS-Accelerator#175]
**Describe the bug**
After deploying the code via the Azure CLI, and updating my SaaS technical details, I get the following error in the UI, when I subscribe and click on the Configure Account Now button: "Error 500 : ClientSecretCredential authentication failed: Value cannot be null. (Parameter 'clientSecret')". I am authenticated, and am able to access the empty subscriptions view.

**To Reproduce**
1. Deploy application via Azure CLI.
2. Update SaaS technical details and republish.
3. Add a new subscription via Azure Portal.
4. Click on the Configure Account Now button.

**Expected behavior**
Expect a landing page with details of the subscription and a link to complete the subscription.

**Screenshots**
![image](https://user-images.githubusercontent.com/45611869/146037962-bb15bec5-a5f9-4463-90d0-98d6dfa07b6b.png)

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome

**Comment by KenBenjamin** [comment]
@selwynoh Can you tell me what you did to fix this? I'm having the same issue. Thanks :)
