### ISSUE TITLE
Cancel button on App Config Edit screen

### ISSUE THREAD

**Issue by dstarr** [Azure/Commercial-Marketplace-SaaS-Accelerator#177]
**Is your feature request related to a problem? Please describe.**

When clicking "back" on my browser from the App Config edit page I get an error. As expected. But there is no other way to get back to the page without clicking "Save App Config."

**Describe the solution you'd like**
A simple **Cancel** button that takes me back to the main App Config Edit page.

**Describe alternatives you've considered**

A back button

**Additional context**

![MicrosoftTeams-image](https://user-images.githubusercontent.com/64742/146583852-a97435a9-4017-4757-ba4d-ad4fdd64efe6.png)

**Comment by alexdrenea** [comment]
With the PR merged, I think this can be closed now!
