### ISSUE TITLE
Automatic redirection and SSO to the solution once customer is subscribed

### ISSUE THREAD

**Issue by neelavarshad** [Azure/Commercial-Marketplace-SaaS-Accelerator#181]
The landing page is still just an MVP. To get closer to real world scenarios, we can further improve it by adding logic to redirect to the saas solution once the customer subscription status reflects subscribed. This will completely automate the process. Also make sure once the customer is redirected, they are signed in using SSO

**Comment by santhoshb-msft** [comment]
@neelavarshad There is an option to specify saasappurl in the app settings. Not exactly what you are looking for but this way customers can get to the saas app. Closing this for now but if you have more information on this feature or need please let me know, we can reopen.
