### ISSUE TITLE
Document Email Setup

### ISSUE THREAD

**Issue by dstarr** [Azure/Commercial-Marketplace-SaaS-Accelerator#188]
We need instructions on how to set up email.

**Comment by Bolleman** [comment]
I filled out the Application Config with what I thought were fairly obvious settings, but no luck on any email notifications.
Any quick tips in advance of the official documentation?  Thanks!

![image](https://user-images.githubusercontent.com/8999611/155040648-0fcf9b2b-2aa5-4c1d-8efc-e4913fef7b9f.png)

**Comment by Bolleman** [comment]
Figured this out, here are the quick tips in case anyone else is looking for the same:
- If you're using an O365 account, make sure you turn on [SMTP auth for the user/mailbox](https://docs.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/authenticated-client-smtp-submission#use-the-microsoft-365-admin-center-to-enable-or-disable-smtp-auth-on-specific-mailboxes) and wait an hour for it to take effect.
- Configure the admin email address to receive the notifications, see [this documentation](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Publisher-Experience.md#subscription-events)
