### ISSUE TITLE
Where are the Nuget packages ?

### ISSUE THREAD

**Issue by ameyasubhedar** [Azure/Commercial-Marketplace-SaaS-Accelerator#198]
**Describe the bug**
I could not find the Nuget packages for SDK Client, Models and API ? 

I found Marketplace.SaaS.Client in Nuget but not sure if this is the official package, it was last updated about 12 months ago !

**Comment by code4clouds** [comment]
Hi @ameyasubhedar - there is no official nuget package for the client libraries, but it is in the works.

The client libraries for .NET can be found here:
https://github.com/microsoft/commercial-marketplace-client-dotnet
