### ISSUE TITLE
What is the difference between beneficiary and purchaser ?

### ISSUE THREAD

**Issue by ameyasubhedar** [Azure/Commercial-Marketplace-SaaS-Accelerator#199]
As per the Microsoft [docs](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-subscription-api) the resolved subscription has 2 fields beneficiary and purchaser. Its not clear whats the difference and which one the apps needs to use to validate the API request while resolving the subscription !

![image](https://user-images.githubusercontent.com/13166236/155765649-199a8c06-ee81-4027-9e88-8baa3097f1f5.png)

**Comment by olsoro0** [comment]
There is an explanation for it in the same [doc](https://docs.microsoft.com/en-us/azure/marketplace/partner-center-portal/pc-saas-fulfillment-subscription-api#get-httpsmarketplaceapimicrosoftcomapisaassubscriptionsapi-versionapiversion):
  "beneficiary": { // email address, user ID and tenant ID **for which SaaS subscription was purchased.**
        "emailId": " test@contoso.com",
        "objectId": "<guid>",
        "tenantId": "<guid>",
        "pid": "<ID of the user>"
      },
      "purchaser": { // email address, user ID and tenant ID **that purchased the SaaS subscription. These could be different from beneficiary information for reseller (CSP) purchase**
        "emailId": " test@contoso.com",
        "objectId": "<guid>",
        "tenantId": "<guid>",
        "pid": "<ID of the user>"
      },
