### ISSUE TITLE
Marketplace.SaaS.Client - The downstream apps cannot access any of the SaaS models. 

### ISSUE THREAD

**Issue by apspi** [Azure/Commercial-Marketplace-SaaS-Accelerator#210]
**Describe the bug**
[Marketplace.SaaS.Client](https://www.nuget.org/packages/Marketplace.SaaS.Client) The downstream apps cannot access any of the SaaS models. The current design forces the apps to be server deployed as there is no public constructor for any models. This seems a weird design constraint.

For e.g.

```
        internal ResolvedSubscription()
        {
        }

        internal ResolvedSubscription(Guid? id, string subscriptionName, string offerId, string planId, long? quantity, Subscription subscription)
        {        
        }

        internal static ResolvedSubscription DeserializeResolvedSubscription(JsonElement element)
        {           
        }
```

SPA with backed API that works with Microsoft SaaS API needs access to the front-end models. 

Even the standard JsonSerializer does not work because of how the models are designed.

So I have 3 critical issues here:

1. The models should be independent of deployment strategy. It makes no sense for models to assume how customer Apps are deployed (Server, SPA, etc)
2. Provide public constructors and JsonPropertyName for Models to ensure the design and API consistency.
3. Backend API or server deployed apps will use the client classes with the secret to communicate with Microsoft SaaS API, and front-end or SPA will use models based on JSON serialization to render UI.

**Comment by santhoshb-msft** [comment]
@apspi This might be better to track on the dotnet library project. Closing this here and will open one at https://github.com/microsoft/commercial-marketplace-client-dotnet
