### ISSUE TITLE
How to validate Webhook payload ?

### ISSUE THREAD

**Issue by ameyasubhedar** [Azure/Commercial-Marketplace-SaaS-Accelerator#214]
How do I validate the marketplace webbook payload and reject the once that are not triggered by Microsoft ?

I could not find any API that will validate the webhook payload ?

Please provide an example on how to achieve this validation.

**Comment by santhoshb-msft** [comment]
Hi @ameyasubhedar  please find more information on securing webhook here https://github.com/microsoft/Mastering-the-Marketplace/blob/main/saas/README.md#securing-a-simple-saas-webhook-in-net
