### ISSUE TITLE
Access logs via admin interface

### ISSUE THREAD

**Issue by dstarr** [Azure/Commercial-Marketplace-SaaS-Accelerator#224]
**Is your feature request related to a problem? Please describe.**
Partners are frustrated by requiring them to access logs via SQL tools

**Describe the solution you'd like**
Would be great to have a page allowing browsing of the logs, maybe even searching. Could be something simple like %term% in SQL

**Comment by santhoshb-msft** [comment]
@dstarr this is fixed in #269 , should we close this?

**Comment by dstarr** [comment]
I believe this enhancement ir already delivered as noted above. @code4clouds please confirm and close issue if appropriate.

**Comment by code4clouds** [comment]
Yeap... There is a button on the admin page to show logs.

![image](https://user-images.githubusercontent.com/29647050/205676436-fd8cffa0-916d-4778-ab8b-ba4e62f41bf9.png)
