### ISSUE TITLE
License message on Manage Usage Page

### ISSUE THREAD

**Issue by dstarr** [Azure/Commercial-Marketplace-SaaS-Accelerator#225]
**Describe the bug**
The first time accessing the Manage Usage page there is a message shown about requiring subscriptions. This is obviouslu not true and it confusing to partners.

It does NOT appear after sending a metered billing event.

**To Reproduce**
In the admin portal:
1. A new subscription moves into Subscribed state
2. Click on Manage Usage
3. A message is shown about subscriptions being needed
4. Send a billing event
5. The message goes away

**Expected behavior**
No subscriptions message is shown.

**Comment by santhoshb-msft** [comment]
![image](https://user-images.githubusercontent.com/63607175/179276425-9e80eff6-0ac2-4ea9-83a4-fe62290893e7.png)

**Comment by santhoshb-msft** [comment]
I think the right message should be "No subscriptions usage events."

**Comment by dstarr** [comment]
I think the right message is no message. If there have been no usage events, that should be self-evident because they are not present. Just my POV.

**Comment by santhoshb-msft** [comment]
Sure, we can go with your thoughts and leave it blank. cc: @louisephilardeau
