### ISSUE TITLE
Application Config - Add message on this page to restart server

### ISSUE THREAD

**Issue by dstarr** [Azure/Commercial-Marketplace-SaaS-Accelerator#226]
**Is your feature request related to a problem? Please describe.**
After editing a setting on the Settings page, please display a message to the user stating they must restart the web application for the changes to take effect.

**Describe the solution you'd like**
After editing an item in the settings, the message displays
OR
The message is present at the top of the page all the time. "After changing a setting..."

**Describe alternatives you've considered**
Message becomes present after editing a setting
Message is shown all the time

**Comment by dstarr** [comment]
Fixed

**Comment by santhoshb-msft** [comment]
Can we close this, @dstarr ?

**Comment by dstarr** [comment]
Closed. Thank you.

*David Starr*
ElegantCode.com // @elegantcoder <https://twitter.com/elegantcoder>
linkedin.com/in/davidstarr
