### ISSUE TITLE
Create Docker images for the sample components.

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#27]
**Is your feature request related to a problem? 
Facilitate the deployment of the environment using Dockerfiles.

**Describe the solution you'd like**
I would like all the components to be deployed as docker containers

**Describe alternatives you've considered**
VMs, but docker images are the best solutions to deploy the sample on Kubernetes environments.

**Additional context**

**Comment by santhoshb-msft** [comment]
@code4clouds from our other conversation, should we still consider this or close?

**Comment by santhoshb-msft** [comment]
Closing for now, might consider in future.
