### ISSUE TITLE
Error when using the new 3 year SaaS subscription

### ISSUE THREAD

**Issue by chuckthompsonprofisee** [Azure/Commercial-Marketplace-SaaS-Accelerator#290]
**Describe the bug**
We have a SaaS offer with a plan using the new 3 year subscription and when the customer goes to configure account, it redirects to our accelerator, but the get an error Error 500: Unknown TermUnitEnum value.  Actual value was P3Y.  we are using the code from the 4.1.0 branch btw

**To Reproduce**
go to private offer in azure market place
Pick the offer
click subscribe for a plan that is 3Year
click configure
then when redirected to the accelerator, you get that error

**Expected behavior**
Should take then to the order form

![image](https://user-images.githubusercontent.com/63325482/182034968-6b04e253-a52a-43e8-abaa-0bff682550c0.png)

**Comment by santhoshb-msft** [comment]
Ack, add the option here once the client library is updated.
