### ISSUE TITLE
Documentation for Deploy web applications and SQL Azure database using an ARM template

### ISSUE THREAD

**Issue by MichaelSchreiber** [Azure/Commercial-Marketplace-SaaS-Accelerator#291]
**Is your feature request related to a problem? Please describe.**
To me it is unclear how to obtain the values for

- AD Application ID
- AD Application Secret
- ADMT Application ID

My understanding is that these are created during the install.
They are also not required for the other deployment options.

**Describe the solution you'd like**
I would like a description on how to obtain these parameters.

**Describe alternatives you've considered**

**Additional context**

**Comment by alexdrenea** [comment]
Hi Michael.

For the AD ApplicationID and ADMT Application ID, those values are present in the output of the deployment script (at the end of running).

The ClientSecret is not written in the console output for privacy / security reasons. It is added to the KeyVault and referenced in the app automatically. In theory, you should not need it, but if you do, then you can read it from the KeyVault (if you're using v6 of the accelerator) or from the admin portal web app configuration section (if you're using a version before v6)

**Comment by MichaelSchreiber** [comment]
Hi Alex,

Thank you for answering.
Yes, the script shows the values **after** the deployment. My question was about the ARM template. There the values had been requested **upfront**. However, the link to the ARM template on https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Advanced-Instructions.md#deploy-web-applications-and-sql-azure-database-using-an-arm-template to https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/deployment/Templates/deploy.json does not work anymore. So, I think the ARM template is obsolete now.

**Comment by ryanperrymba** [comment]
Hi,

**Confirming @MichaelSchreiber's note that the ARM template which should be found at /deployment/Templates/deploy.json is not there.**  

Also, attempting to install using the basic instructions on using Azure Powershell ran into time out issues, wherein Azure would close the powershell session.  If there is a way to prevent Azure from closing the session, it would be helpful to add to instructions.

Will continue on with lower sections to see if I can figure out how to set this up.  Thanks for all the hard work the team has put into this.

**Comment by santhoshb-msft** [comment]
Hi @MichaelSchreiber /@ryanperrymba,
Thank you for raising this issue.
For now, we are hiding the advance installation docs to update to the latest changes. We will keep this issue open untill we have the docs updated.

**Comment by alexdrenea** [comment]
@MichaelSchreiber Apologies for missing your reply (please feel free to @ me so I receive a notification)

You are correct, we do not deploy using the ARM template anymore as it has been replaced by the PowerShell script. The PS script contains all functionality (and extra) from the ARM template and that includes creating the App Registrations needed for the Marketplace integration. You can also supply your own App Ids if you already have them

**Comment by MichaelSchreiber** [comment]
@alexdrenea Thank you for the explanation. From my point of view the issue can be closed.
