### ISSUE TITLE
The storage account named amptmpstorage210 is already taken. (Parameter 'Name')

### ISSUE THREAD

**Issue by MichaelSchreiber** [Azure/Commercial-Marketplace-SaaS-Accelerator#293]
**Describe the bug**
I tried to install multiple times. In about one out of three times I receive the message:
The storage account named amptmpstorage### is already taken. (Parameter 'Name')
Where ### is a random three digit number.
Unfortunately, at this time an app registration was already created (not entirely sure about that).

**To Reproduce**
Try the installation multiple times (with different names).

**Expected behavior**
The storage account can be created. The generated part of the account name should be long enough to ensure a unique name and if a generated name is already used, a new name should be generated.
Documentation: Users should be advised to delete the storage account manually in case the installation fails.

**Screenshots**

**Environment (please complete the following information):**
This happens in CloudShell and Powershell (Windows 11, PowerShell 7.2.5).
    
**Additional context**
Issue #292
[Installed Modules.txt](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/files/9249643/Installed.Modules.txt)
When the installation fails, hangs or is cancelled, the storage account is not deleted. Hence the names remain used until the user manually deletes the storage account.

**Comment by santhoshb-msft** [comment]
I think we should increase the randomness of the storage account name to start with.

**Comment by MichaelSchreiber** [comment]
#236 seems to relate to the same topic.
