### ISSUE TITLE
Warn user about reusing the current keyvault

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#315]
**Is your feature request related to a problem? Please describe.**
Installer should as customer if they want to keep the current keyvault or stop after finding an existing keyvault deployed with the same name.

**Describe the solution you'd like**
CLI will stop and ask
A flag in the command line (i.e --skip-kv) should skip this prompt and continue with existing KV.  Default (no flag) is to stop and ask.

**Comment by santhoshb-msft** [comment]
@code4clouds - should we maybe add an additional optional parameter so they can pass an existing kv name?

**Comment by code4clouds** [comment]
Yes... or it find it exist (from previous install) ask to reuse it.
