### ISSUE TITLE
Admin emails during install

### ISSUE THREAD

**Issue by dstarr** [Azure/Commercial-Marketplace-SaaS-Accelerator#320]
**Describe the bug**

When I tried to add multiple emails to the plan Success/Failure Event Emails, I used the following notation: "[email@example.com,other@example.com](mailto:email@example.com,other@example.com)" and I got an error stating that ',' was an incorrect character in the email header. After a few trials I've realized that I needed a space after the comma, i.e., "[email@example.com, other@example.com](mailto:email@example.com,%20other@example.com)".

**To Reproduce**
1. During install use "email@example.com,other@example.com"
2. Causes error

**Expected behavior**
Should be SEMI-COLON delimited field with trim() on all values retued from a split.

**Environment (please complete the following information):**
 - Are you using the CloudShell? Yes
    
**Additional context**
Reported from partner Signly.co

**Comment by santhoshb-msft** [comment]
@usman-ms
1. Check to install with multiple emails and see if its working
2. Add multiple success/failure  event emails with a semicolon delimiter on the plan and check if the email notifications are sent out accordingly

**Comment by usmanm-ms** [comment]
@santhoshb-msft 
I have verified this to be working on the client installation and can be closed
