### ISSUE TITLE
Offer Name column in Admin and Customer portal

### ISSUE THREAD

**Issue by alexdrenea** [Azure/Commercial-Marketplace-SaaS-Accelerator#344]
**Is your feature request related to a problem? Please describe.**
Admin Portal:
- When partner has multiple offers, it is hard to tell from the subscriptions page, which offer they are subscribed to.
Customer Portal:
- When subscribing to multiple offers from the same provider, I can't tell which offer each subscription is for.

**Describe the solution you'd like**
Admin Portal:
- Add Offer Name as a new column in the subscriptions table on the subscriptions page
- Add Offer Name in the subscription details page.
- [Optional] remove Subscription Id as a column since most times it's not needed "At a glance". Id can remain on the subscription Details page.

Customer Portal
- Add Offer Name as a new column in the subscriptions table on the subscriptions page

**Describe alternatives you've considered**
n/A

**Comment by santhoshb-msft** [comment]
@alexdrenea do you think this will cover #218? I marked it as duplicate but I can reopen that if this doesnt cover.
