### ISSUE TITLE
Customer Initiated Change Plan succeeds even when AcceptSubscriptionUpdate is False

### ISSUE THREAD

**Issue by alexdrenea** [Azure/Commercial-Marketplace-SaaS-Accelerator#348]
**Describe the bug**
"AcceptSubscriptionUpdates" flag is not respected. Customer initiated plan change goes though even if the flag is set to "false".
The application log shows "plan change request rejected successfully' but the plan is changed in the Azure Portal.

**To Reproduce**
1. Go to Application Settings and ensure "AcceptSubscriptionUpdates" is set to false.
2. Navigate to Azure Portal, and initiate a change plan to one of the subscriptions

**Expected behavior**
Change plan does not go though

**Screenshots**
Change Plan is successfull

**Additional context**
Based on initial debugging and looking at the logs, it looks like we are sending the correct response to the Marketplace API UpdateOperationStatus endpoint but that is not taken into account.

**Comment by santhoshb-msft** [comment]
Thanks for raising this @alexdrenea 
This is a bug but not from Accelerator, it is the current behavior of the SaaS webhook.
I would want to close this but we keep an eye on and re check once the SaaS webhook behavior is fixed in the near future.

**Comment by alexdrenea** [comment]
Is there a ticket opened with the Marketplace team to track this? This is pretty serious bug as it allows customers to change their plans without publisher approvals.

**Comment by WiluGIT** [comment]
@alexdrenea @dstarr @santhoshb-msft any updates in this issue? It still seems, that problem persists.

**Comment by mivra** [comment]
I also came across this issue. It seems like a problem in Operations API. The UpdateOperationStatusAsync is called and should switch the operation to Failure status but it does not.

**Comment by santhoshb-msft** [comment]
Hi @mivra - If I understood this correctly, the plan change operation succeeds even after the patch operation returned Failure?

**Comment by santhoshb-msft** [comment]
@mivra  - this is plan to implement, you will see changes coming soon on this change.

**Comment by santhoshb-msft** [comment]
> I also came across this issue. It seems like a problem in Operations API. The UpdateOperationStatusAsync is called and should switch the operation to Failure status but it does not. Possible workaround - the change plan operation will fail if the webhook returns non 2xx response code.


@mivra - this is plan to implement, you will see changes coming soon on this change.

**Comment by WiluGIT** [comment]
> Hi @mivra - If I understood this correctly, the plan change succeeds even after the patch operation returned Failure?

@santhoshb-msft 
@mivra 

Exactly, that is current behaviour of Operations API. Even if you successfully send "Failure" in Change Plan/Change Quantity event, action still succeeds.

I have also tried workaround with returning response code != 200. It was once working, once not. It's very important for publishers, to be able to reject forbidden actions on their offer and it should work perfect on every Operations API call.

**Comment by santhoshb-msft** [comment]
@WiluGIT - Are you patching operation AFTER returning 200 on webhook call? If yes and still seeing the issue, I recommend raising a support ticket on Partner Center.

workaround =" I have also tried workaround with returning response code != 200" - what did you return on the work around?

**Comment by WiluGIT** [comment]
@santhoshb-msft I've reimplemented Webhook logic as you in https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/issues/437. Everything is working as expected. Patch is failing operation if i send Failure update. So the case was patching operation AFTER returning 200 as you said before. Why this solution isn't merged to main branch yet?

**Comment by santhoshb-msft** [comment]
Hi @WiluGIT we have a couple of different ways to reject, we are analyzing the best way to reject. There will be another PR on this which a little bit of different business logic. I will keep you posted. Thanks 
We are trying to get this in for our EOM release.

**Comment by santhoshb-msft** [comment]
This is now fixed in 7.0.0
