### ISSUE TITLE
Customer Portal Change Plan / Quantity functionality

### ISSUE THREAD

**Issue by alexdrenea** [Azure/Commercial-Marketplace-SaaS-Accelerator#350]
**Describe the bug**
In the Customer Portal, we are disabling the Change Plan / Quantity functionality based on the wrong application setting:

https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/1d2805fd489595566fe6ab52b279947ea043d3f4/src/CustomerSite/Views/Home/Subscriptions.cshtml#L64

If I understand the settings correctly, we should be looking at "AcceptSubscriptionUpdates" and not "IsAutomaticProvisioningSupported" to show/hide the Change Plan / Quantity options.

**Comment by dstarr** [comment]
Closing. Fixed in PR #399
