### ISSUE TITLE
Can't change Quantity in Admin Portal

### ISSUE THREAD

**Issue by alexdrenea** [Azure/Commercial-Marketplace-SaaS-Accelerator#354]
**Describe the bug**
The Change Quantity Popup does not load correctly in the Admin Portal

**To Reproduce**
1. Go to Admin Portal
2. Click on 'change quantity"

**Expected behavior**
Able to change quantity 

**Screenshots**
![image](https://user-images.githubusercontent.com/8275679/200973969-688fb495-ddc6-41c3-9d22-a2398d5b8a80.png)

**Additional context**
This is likely due to using an invalid SubscriptionService Method to fetch the subscription Details in `HomeController` / `SubscriptionQuantityDetail` method (should use `subscriptionService.GetSubscriptionsBySubscriptionId`)

**Comment by santhoshb-msft** [comment]
![image](https://user-images.githubusercontent.com/63607175/204965172-bc109041-a781-4fd9-8a88-7735695fc5e0.png)

Hi @alexdrenea - works fine on my instance, could be a specific use case where this might fail. Additional Repro steps would help please.

**Comment by santhoshb-msft** [comment]
@alexdrenea as per my above comments, closing this for now, please let me know if can repro this, we will reopen and fix.
