### ISSUE TITLE
Remove SaaSApiConfiguration__SupportmeteredBilling from portal app creation

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/Commercial-Marketplace-SaaS-Accelerator#361]
Remove SaaSApiConfiguration__SupportmeteredBilling from portal app creation as there is no relevance. 

https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/f57ff86490281a4fe4098c45c459ca717e5e139e/deployment/Templates/Deploy.ps1#L283

**Comment by alexdrenea** [comment]
For that matter, we could also remove the `KnownUsers` config from the customer portal!

**Comment by alexdrenea** [comment]
fixed in #398

**Comment by santhoshb-msft** [comment]
Thanks for the comment @alexdrenea , this got fixed in #391 
I will attach to the PR.
