### ISSUE TITLE
Fix compilation warnings that show up when deploying solution

### ISSUE THREAD

**Issue by alexdrenea** [Azure/Commercial-Marketplace-SaaS-Accelerator#363]
**Is your feature request related to a problem? Please describe.**
This is not a blocking issue, but every time we run the deployment script, we see 6 warnings when compiling and building packages for the Admin Portal and Customer portal.
We should fix the warnings.

**Describe the solution you'd like**
Fix the warnings

**Describe alternatives you've considered**
We could suppress the warnings but fixing them would be clearly better :)

**Additional context**
![image](https://user-images.githubusercontent.com/8275679/205095195-7080fb6a-43a4-4d2f-9760-477ac15746d9.png)

**Comment by dstarr** [comment]
Classifying this as a refactoring. It could have gone feature, but I had to pick one.
