### ISSUE TITLE
Installation instructions error

### ISSUE THREAD

**Issue by ichivers** [Azure/Commercial-Marketplace-SaaS-Accelerator#386]
**Describe the bug**
The installation instructions script fails

.\Deploy.ps1: 
Line |
   5 |  .\Deploy.ps1 `
     |  ~~~~~~~~~~~~
     | The term '.\Deploy.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

The script in the installation instructions has a bug:

dotnet tool install --global dotnet-ef; `
git clone https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator.git -b 6.0.1 --depth 1; `
cd ./Commercial-Marketplace-SaaS-Accelerator/deployment; `
Connect-AzureAD -Confirm; `
.\Deploy.ps1 `
 -WebAppNamePrefix "marketplace-SOME-UNIQUE-STRING" `
 -SQLServerName "marketplace-SOME-UNIQUE-STRING" `
 -SQLAdminLogin "adminlogin" `
 -SQLAdminLoginPassword "" `
 -PublisherAdminUsers "user@email.com" `
 -ResourceGroupForDeployment "MarketplaceSaasGitHub" `
 -Location "East US"; `

Should be (missing Templates folder in the path)

dotnet tool install --global dotnet-ef; `
git clone https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator.git -b 6.0.1 --depth 1; `
cd ./Commercial-Marketplace-SaaS-Accelerator/deployment; `
Connect-AzureAD -Confirm; `
.\Templates\Deploy.ps1 `
 -WebAppNamePrefix "marketplace-SOME-UNIQUE-STRING" `
 -SQLServerName "marketplace-SOME-UNIQUE-STRING" `
 -SQLAdminLogin "adminlogin" `
 -SQLAdminLoginPassword "" `
 -PublisherAdminUsers "user@email.com" `
 -ResourceGroupForDeployment "MarketplaceSaasGitHub" `
 -Location "East US"; `

**To Reproduce**
Follow the installation instructions

**Expected behavior**
Shouldn't error on cannot find the deploy script

**Comment by santhoshb-msft** [comment]
Thank you for raising this @ichivers.
Fixed to use the new release version which used mitigate this error

**Comment by santhoshb-msft** [comment]
Updated to new version, Close pending PR merge.
