### ISSUE TITLE
Logging on console and application logs

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/Commercial-Marketplace-SaaS-Accelerator#393]
**Is your feature request related to a problem? Please describe.**
Currently some client-sde logging(example: fetchallsub) and AppLog in DB logging is missing. It is hard to know the errors when they happen.

**Describe the solution you'd like**
Implement logging on client side where applicable and applog in db logging

**Describe alternatives you've considered**

**Additional context**

**Comment by alexdrenea** [comment]
Added application logs when `FetchAllSubscription` fails as part of #399

**Comment by santhoshb-msft** [comment]
We can ignore the console logging for now. Lets just keep it to app logs.
