### ISSUE TITLE
Using the code first migrations with Seed is failing.

### ISSUE THREAD

**Issue by robertstewartnz** [Azure/Commercial-Marketplace-SaaS-Accelerator#401]
**Describe the bug**
Looks like the format for 
`DateTime.Now` 
is localising the format to en-NZ day/month/year which is causing an issue in the db.

Suggest supplying an explicit format to match what the database is expecting. 

**To Reproduce**
1. Create new sql database.
2. Run CF migrations
3. See error

**Expected behavior**
CF migration should complete without errors

**Environment (please complete the following information):**
 - Are you using the CloudShell?
 - If not using the CloudShell:
    - OS: Windows 11
    - Visual Studio Version 17.4.0 Preview 5.0
    - New Zealand

**Comment by santhoshb-msft** [comment]
Closing as duplicate to #475
