### ISSUE TITLE
.ico and .png logos fail to download.

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#408]
**Describe the bug**
![image](https://user-images.githubusercontent.com/29647050/207467297-35156dc3-749c-4d27-8ee2-47ba226edece.png)

**To Reproduce**
1. Run the install script using your own logos.

**Comment by alexdrenea** [comment]
@Julio, you might be using an older version of the deployment script. 
The latest version, on main branch, has this issue corrected by using proper pathing ( / not \) so that it works universally across Unix and Windows.
