### ISSUE TITLE
Renaming of Solution and Client Library

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#48]
Update and move the client library code to its new repository.
Add submodule of the client library repo to this repo.
Update documentation to provide developers information on how to clone with submodules.

**Comment by santhoshb-msft** [comment]
@code4clouds - do you think if this is still relevent?

**Comment by code4clouds** [comment]
Not anymore...  I think this has been addressed.
