### ISSUE TITLE
Login Error while activating a PendingActivation

### ISSUE THREAD

**Issue by gjain-sag** [Azure/Commercial-Marketplace-SaaS-Accelerator#483]
**Describe the bug**
With email activated for all workflow status getting login error once click on Activate for a Pending Activation

**To Reproduce**
1. Go to admin console
2. Activate email for all status of subscription workflow
3. Click Activate for a Pending Activation susbscription
4. Getting login error on UI

**Expected behavior**
User should receive email for Activation as well as admin should be redirected to confirmation page.

**Screenshots**
![image](https://user-images.githubusercontent.com/75057599/234490663-7b555f3f-57f9-44df-a650-fdb1d7897570.png)

**Comment by santhoshb-msft** [comment]
Thank you for raising this issue, @gjain-sag . We will review.

**Comment by bit-twit** [comment]
I get the same, on v7.0.0. The Activation API call is stuck in pending for a while and then times out in the client portal. On Saas Admin side I see the same time out error in application logs, nothing else. It started to happen once I enabled email notifications

**Comment by pooranoayaw** [comment]
Any update on this? we are also facing this issue

**Comment by bit-twit** [comment]
It was just smtp misconfiguration for me, once I configured it correctly it worked.

**Comment by santhoshb-msft** [comment]
Thank you for the update @bit-twit 
It is generally a misconfiguration, if logs are enabled I recommend looking into server/app logs or try to debug locally.
Closing this as no pending action from our side. Please reopen with more details if we can help any further.
