### ISSUE TITLE
admin portal 500 after change of SQL admin password

### ISSUE THREAD

**Issue by rgaborgithub1** [Azure/Commercial-Marketplace-SaaS-Accelerator#489]
In order to regain access to an orphaned deployment, our devops had to add admin users to the database - after resetting the password. But by this the service is not able to connect to the DB (http 500).
Where/how can we fix this connection issue without a complete redeployment?

**Comment by santhoshb-msft** [comment]
Hi @rgaborgithub1 if the password has been changed, please update that in your keyvault

**Comment by santhoshb-msft** [comment]
Please reopen if you have further questions
