### ISSUE TITLE
Scheduler UI doesn't work with time zones

### ISSUE THREAD

**Issue by jeernest** [Azure/Commercial-Marketplace-SaaS-Accelerator#497]
**Describe the bug**
New Scheduler UI stores StartDate in local time zone, but the scheduler itself works in UTC. Actually, there is several bugs.

**To Reproduce**
1. Make sure that time zone of your browser is not UTC, let's say we are in UTC+2
2. Go to /Scheduler/NewScheduler
3. Fill all fields and select One time job
4. Let's say that today is 5/18/2023 3:33 PM so as a First Run Date enter 5/18/2023 4:00 PM
5. Click on Add Scheduler Usage Task
6. Error 1 - see the error saying 'The value must be greater 5/18/2023 3:33 PM or later', which is not true
7. see the time in the First Run Date, which was shifted 2 hours back to 5/18/2023 2:00 PM (that's probably the reason for the error message)
8. Another try, as the First Run Date enter 5/18/2023 6:00 PM
9. Click on Add Scheduler Usage Task
10. See the time in the First Run Date, which was shifted 2 hours back to 5/18/2023 4:00 PM
11. The scheduler is stored to DB with StartDate 5/18/2023 4:00 PM
12. Wait until 5/18/2023 4:00 PM UTC+2
13. Error 3 - Check kudu scheduler webjobs logs and see that the job was not executed
````
[05/18/2023 14:00:04 > 355206: INFO] MeteredExecutor Webjob Started at: 5/18/2023 2:00:04 PM
[05/18/2023 14:00:10 > 355206: INFO] ==== Checking all OneTime scheduled items at 5/18/2023 2:00:00 PM UTC. ====
[05/18/2023 14:00:10 > 355206: INFO] Item Id: 6 Expected NextRun : 5/18/2023 4:00:00 PM SubId : 823991aa-0322-457a-cbeb-bba06a12f5fd Plan : portnox-cloud-test2 Dim : tacacs_admin Start Date : 5/18/2023 4:00:00 PM NextRun : TimeDifferenceInHours : -2
[05/18/2023 14:00:10 > 355206: INFO] Item Id: 6 future run will be at 5/18/2023 4:00:00 PM UTC.
````

**Expected behavior**
The scheduler is stored correctly with StartDate 5/18/2023 2:00 PM UTC.
The metered job is is executed at 5/18/2023 4:00 PM UTC+2

**Environment (please complete the following information):**
 - Are you using the CloudShell? no
 - If not using the CloudShell:
    - OS: Windows, Firefox, Chrome

**Comment by s8mathur** [comment]
My browser is in Asia/Kolkata time zone and the simple task of "Just send off a one-time overage report NOW or ASAP" is impossible to accomplish using the data/time input field . See attached. 
In addition to refactoring the data/time form field input UI, the "OneShot" timer option should lead to "fire off ASAP" checkbox button to make things easier; i.e no need to explicitly set a data+time. 
![BrokenTimeScheduling](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/5669765/2f29ec01-d3a1-4d48-b199-89ca3970af6e)

**Comment by santhoshb-msft** [comment]
@jeernest thank you for raising this.
Error 1/2 should be fixed with #518 
For the Error 3, I see the current UTC time is 2pm , so the trigger would have executed at 4

**Comment by santhoshb-msft** [comment]
@jeernest  please let us know anything further we could help here.

**Comment by jeernest** [comment]
Thank you @santhoshb-msft, it works well. Just one small issue. If user enters 5:15 pm the system rounds the time to 5:00 pm, which is in the past so the trigger will not be executed.

Generally, triggers not executed in the past are problematic the same way as failed triggers. If there's an error, the job doesn't schedule next run time.
