### ISSUE TITLE
Unsubscribing user results in OOPS! you don't have access

### ISSUE THREAD

**Issue by git657** [Azure/Commercial-Marketplace-SaaS-Accelerator#502]
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/109476070/8ab6baab-0748-4121-849e-9e0524b5e077)

try to unsubscribe a user, I get the error "Oops! you don't have access to this site when I am logged on and if I refresh the subscription is unsubscribed

**Comment by santhoshbomma9** [comment]
Hi @hemmy could you please elaborate on what is unsubscribing a user? You mean deleting a user? So you delete any user and you get this message? Any additional repro steps would help helpful please.

**Comment by santhoshb-msft** [comment]
Hi @hemmy could you please elaborate on what is unsubscribing a user? You mean deleting a user? So you delete any user and you get this message? Any additional repro steps would help helpful please.

**Comment by hemmy13** [comment]
go to subscriptions on the admin portal, if there is a pending subscription and I click subscribe I get the error or if 
I click unsubscribe I get the error as well
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/109476070/faede506-cc84-48b8-b8ff-2c61ae271292)

**Comment by hemmy13** [comment]
@santhoshb-msft

**Comment by santhoshb-msft** [comment]
Probably same as #503 , I recommend to please debug in the local env to see the root of mis configuration

**Comment by santhoshb-msft** [comment]
Hi @git657 I hope you were able to resolve this. Please let us know if you were able to repro this. Closing this for now, but please reopen with some repro steps so we can work towards a resolution if there is any issues. Thank you!

**Comment by rd-snow17** [comment]
@git657 , we are facing similar issue. Were you able to fix it??
