### ISSUE TITLE
The upgrade procedure fails - need to install another dotnet version

### ISSUE THREAD

**Issue by jvystrcil-mama-ai** [Azure/Commercial-Marketplace-SaaS-Accelerator#509]
**Describe the bug**
Yesterday I have installed in Azure Power Shell the accelerator following the instructiuons from docs. This went fine. Today I wanted to upgrade code by running the upgrade [script](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Installation-Instructions.md#update-to-a-newer-version-of-the-saas-accelerator) from docs

**To Reproduce**
Steps to reproduce the behavior run the upgrade script.

```
#### Deploying new database ####
## Retrieved ConnectionString from KeyVault
Build started...
Build succeeded.
You must install or update .NET to run this application.

App: /home/jan/.dotnet/tools/.store/dotnet-ef/7.0.5/dotnet-ef/7.0.5/tools/net6.0/any/tools/netcoreapp2.0/any/ef.dll
Architecture: x64
Framework: 'Microsoft.NETCore.App', version '6.0.0' (x64)
.NET location: /usr/share/dotnet/

The following frameworks were found:
  7.0.5 at [/usr/share/dotnet/shared/Microsoft.NETCore.App]

Learn about framework resolution:
https://aka.ms/dotnet/app-launch-failed

To install missing framework, download:
https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=6.0.0&arch=x64&rid=mariner.2.0-x64
## Generated migration script
## !!!Attempting to upgrade database to migration compatibility.!!!
## Ran compatibility script against database
Invoke-Sqlcmd: /home/jan/Commercial-Marketplace-SaaS-Accelerator/deployment/Upgrade.ps1:84
Line |
  84 |  Invoke-Sqlcmd -inputFile script.sql -ServerInstance $Server -database …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Could not find file '/home/jan/Commercial-Marketplace-SaaS-Accelerator/deployment/script.sql'.
```

The solution for me was to run following to install another version of dotnet
```
wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh; `
chmod +x dotnet-install.sh; `
./dotnet-install.sh -v 6.0.0 -runtime dotnet --architecture x64 ; `
$ENV:PATH="$HOME/.dotnet:$ENV:PATH"; `
dotnet tool install --global dotnet-ef; ` 
```

**Expected behavior**
The script will pass withou errors

**Screenshots**
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/77060463/12310a84-35d2-458a-b09c-8045609993df)

**Environment (please complete the following information):**
 - Are you using the CloudShell? yes, powershell

**Comment by santhoshbomma9** [comment]
Hi @jvystrcil-mama-ai - Thank you for bringing this to our notice. This was due to the cloudshell image upgrade. We have updated the original install script with the above solution proposed and the upgrade should have went fine as well. We will add the same instructions to the upgrade script as well.

**Comment by santhoshb-msft** [comment]
Hi @jvystrcil-mama-ai - Thank you for bringing this to our notice. This was due to the cloudshell image upgrade. We have updated the original install script with the above solution proposed and the upgrade should have went fine as well. We will add the same instructions to the upgrade script as well.

**Comment by jvystrcil-mama-ai** [comment]
That's perfect, thank you for quick fix
