### ISSUE TITLE
No plans listed and 404 at appsource

### ISSUE THREAD

**Issue by quartilesoftware** [Azure/Commercial-Marketplace-SaaS-Accelerator#520]
I’ve just created a default installation of SaaS accelerator in Azure.

I’ve also just published an offer with three plans to the “preview creation” stage in my Microsoft Partner Account Offers. I’ve set the correct tenant ID and application ID in Partner Centre.

I’ve encountered two problems, which may be related.

The first is, in SaaS accelerator, no plans are listed.

The second is, when I use the AppSource preview link to test my offer, after signing in with a Microsoft work or personal account,  I see a 404 / Not found at https://appsource.microsoft.com/callback?code=  (remainder removed).

I can’t find any help or pointers anywhere to direct me to what may be wrong for either issue. Can anyone help me fix this, or guide me to where to look?

**Comment by santhoshb-msft** [comment]
@quartilesoftware - subscriptions/plans/offers information is not loaded in the admin portal if the customer after subscribing wont go to the landing page. On the flip side if you would like to bring that information, please use the fetchallSubscriptions button on the Subscriptions page.

**Comment by quartilesoftware** [comment]
Hi ,

Thanks for your reply.

I tried clicking the “Fetch all subscriptions” button, but that simply displays a successful “Complete” message. There are still no plans, subscriptions or any other details listed. No errors in the application log.

My Partner Centre offering is in preview. I assume that SaaS Accelerator will still be able to retrieve any plans even though the application is not yet live, so we can test things?

The final step of the SaaS Accelerator installation in Azure Powershell displayed an AAD application ID to enter into Partner Centre technical details, which I did. That appears to be the application ID of the <>FulfillmentAppReg in Azure. Is that correct? 

The <>FulfillmentAppReg is also installed with no RedirectURLs. Is that also correct?

I’ve double-checked that the four technical details entered in Partner Centre all match the details provided from the SaaS Accelerator installation result.

In Partner Centre, the landing page URL is correctly configured as 
https://mychosenname-portal.azurewebsites.net/ which, as you say, should be the URL to which the customer is directed after subscribing. 

But, the customer never seems to reach the option to subscribe. All that happens is this:

1.	Click on the “Get it now” button in AppSource
2.	A “Sign in to Microsoft AppSource login dialog appears 
3.	After entering username and password, a 404 is displayed, at the URL https://appsource.microsoft.com/callback?code= <token removed>

The customer never sees the landing page, so far as I can tell.

Any help is gratefully received!

**Comment by quartilesoftware** [comment]
In case anyone else stumbles across this…

I created a Microsoft support ticket.

Their engineering team said “We know there’s sometimes a problem in that area. Try clearing the browser cache”. That removed the 404.

Yep, that old chestnut.

**Comment by quartilesoftware** [comment]
….But that still left the issue of no plans and no subscriptions appearing in the SaaS Accelerator portal…

I had earlier followed the “Lab 2” installation instructions here:
[https://microsoft.github.io/Mastering-the-Marketplace/saas-accelerator/labs/lab2-install/](url)


which say: “Visit the [SaaS Accelerator's installation instructions [page]](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Installation-Instructions.md)
and copy the *basic installation script*.”, which is what I did, and that led to the failure of the installed admin portal to be able to retrieve plans or subscriptions. Because what was crucially missing from that basic script was this note found further down in the advanced instructions:

“ADApplicationID  -  The value should match the value provided for Active Directory Application ID in the Technical Configuration of the Transactable Offer in Partner Center. If value not provided, a new application will be created.”

OK, fair enough, but before running the SaaS Accelerator installation, I had already created an AAD registration, and that existing registration was what was already configured in my Microsoft Partner Offer technical details page. 

So, that’s why there were no plans to list – the SaaS Accelerator parts were trying to use the registration ID of the new AAD registration it created for itself, rather than the one I had already created. And because the recommended basic script has no mention of the ADApplicationID parameter, I ended up with a mis-configured installation.

A minor tweak to the “Lab 2” documentation to make things more explicit for different existing installation environments might be helpful – extending the words describing step 3, which refer to optional parameters.

**Comment by quartilesoftware** [comment]
... And the 404 issue form AppSource has returned after publishing an update to the Offer in Partner Centre. Clearing the browser cache works only intermittently.  I need a robust solution, not an intermittent one.

**Comment by santhoshb-msft** [comment]
@quartilesoftware 
1. thank you for the feedback on installation docs, cc @dstarr for any potential improvements. also there is description on all the parameters you use here https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Installation-Instructions.md#install-script-parameter-descriptions
2. for 404 I would recommend working with partner center support as its not related to the accelerator please.

**Comment by quartilesoftware** [comment]
@santhoshb-msft

Thanks. 

For point 2, yes, I had already contacted support again before my latest comment. My reason for adding a comment about 404 again was to help anyone else in future who may arrive here and be experiencing the same issue.

**Comment by santhoshb-msft** [comment]
Great thank you very much. Closing this for now.
