### ISSUE TITLE
OOPS! You don't have access to the site (when trying to login to admin portal)

### ISSUE THREAD

**Issue by hkhazaal** [Azure/Commercial-Marketplace-SaaS-Accelerator#521]
**Describe the bug**
After installing the application (7.2.1) and it successfully deploys, I am not able to get to the admin portal. The buyer side works (subscribe), but the admin portal to view and manage the subscription displays "you don't have access" ; with Access Denied thrown despite being the owner (checked access within IAM). Tried to install / delete / re-install, but the exact same error. 

**To Reproduce**
1. install accelerator app (using this video: https://www.youtube.com/watch?v=hQJQJu77WhQ )
2. login to ttps://xx-portal.azurewebsites.net/
3. approve "permission requested" prompt
4. redirected to : https://fnxai-admin.azurewebsites.net/Account/AccessDenied 

**Expected behavior**
Expect that I would get access to the admin portal if I am the owner of the resource group where the app is deployed

**Screenshots**
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/8527826/222d02da-e6b9-4765-b093-53e832f27a78)
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/8527826/22ad2888-813d-4480-850e-8b006bdf51b3)

**Environment (please complete the following information):**
 - Are you using the CloudShell? yes

    
**Additional context**
no

**Comment by santhoshb-msft** [comment]
@hkhazaal 
A couple of things
During the install script did you add yourself as the publisheradminuser?
Please check the db -> knownusers table and make sure your account is listed.

**Comment by hkhazaal** [comment]
@santhoshb-msft  ; thank you for the response. I just followed the steps in the guide, but I do not recall adding my specific user as the publisheradminuser. I will review the steps again and check the db. Thanks for the response. Will update on progress

**Comment by hkhazaal** [comment]
Issue resolved - user error (I did not use the correct e-mail address in the PublisherAdminUsers field. I should have used my Azure account e-mail , I had used an alias e-mai

**Comment by Chirag-CG** [comment]
Thank you for the resolution, I was able to debug the same error and succefully setup admin portal!
