### ISSUE TITLE
A live offer and its plans still have the suffix “-preview” in SaaS accelerator.

### ISSUE THREAD

**Issue by quartilesoftware** [Azure/Commercial-Marketplace-SaaS-Accelerator#522]
My offer passed certification today, was published and is now live in the commercial marketplace.
The offer and its plans still have the suffix “-preview” in SaaS accelerator.
I’ve clicked “Fetch all subscriptions” and nothing changes.
What do I have to do to get SaaS Accelerator to display the same up-to-date data as Partner Account and the Marketplace listing?

**Comment by santhoshb-msft** [comment]
Hi @quartilesoftware Have has been any subscriptions on your offer after its live? 
If Yes - Did they goto landing page?
If No, they nothing gets populated unless you have a subscription. Fetch will only help you pull in subscriptions (and its related plans/offers) info.

**Comment by quartilesoftware** [comment]
Hi @santhoshb-msft ,

Thanks. 
No - the offer was published less than 12 hours ago. Getting paying customers in the first twelve hours of business would be pretty remarkable ;-)

**Comment by santhoshb-msft** [comment]
Closing this as no other follow up questions
