### ISSUE TITLE
Error on Invoke-SqlCmd (line no. 346/347) - Login failed for user 'saasdbadminXXX'.

### ISSUE THREAD

**Issue by ashisa** [Azure/Commercial-Marketplace-SaaS-Accelerator#523]
**Describe the bug**
Deploying the accelerator throws the error mentioned above

**To Reproduce**
1. Run the installation commands as mentioned in the documentation 
2. When the script executes the line no. 299/300 in Deploy.ps1, it prompt to select an option to select the database backup redundancy and when selecting 'no' at the prompt, it fails to create the database and does not throw any errors. However, when the script gets to line no. 347, it fails with the error - Login failed for user 'saasdbadminXXX' since the database doesn't exist.

**Expected behavior**
Deployment should complete without errors

**Screenshots**
None

**Environment (please complete the following information):**
 - Are you using the CloudShell? Yes
 - If not using the CloudShell:
    - PowerShell version
    - Modules installed
    
**Additional context**
Solution - change the following line in the script -
az sql db create --resource-group $ResourceGroupForDeployment --server $SQLServerName --name $SQLDatabaseName  --edition Standard  --capacity 10 --zone-redundant false --output $azCliOutput

To -
az sql db create --resource-group $ResourceGroupForDeployment --server $SQLServerName --name $SQLDatabaseName  --edition Standard  --capacity 10 --zone-redundant false --backup-storage-redundancy Local --output $azCliOutput

**Comment by pooranoayaw** [comment]
Any update on this? we are also facing this issue

**Comment by santhoshb-msft** [comment]
@ashisa @pooranoayaw I am unable to repro this. Script doesnt ask me for anything during the DB create. anything else you can help with to repro this?

**Comment by santhoshb-msft** [comment]
Awaiting to see any other inputs for me to repro this with the current instructions.

**Comment by santhoshb-msft** [comment]
@ashisa 
Please let us know if there anything else we can help with.

**Comment by santhoshb-msft** [comment]
Closing this as no response, please feel free to reopen when the issue arises.
