### ISSUE TITLE
Customer Site/Landing Page will not update

### ISSUE THREAD

**Issue by dillondigitals** [Azure/Commercial-Marketplace-SaaS-Accelerator#525]
Describe the bug
Deploying the accelerator upgrade script runs without errors except "fatal: destination path XXXX already exists and is not an empty directory."

To Reproduce

  1.  Make a change to __LandingPage.cshtml and change "Welcome" to "Thank You" Line 208
  2. Commit and push changes to remote GitHub repo
  3. Run the upgrade commands as mentioned in the documentation in azure portal powershell

Expected Result:
The landing page Shows "Thank You" instead of "Welcome" when navigating to the azure domain. 

Additional context
Changes are seen when ran locally.
Changes to code are reflected on remote GitHub repo when pushed
reference video https://www.youtube.com/watch?v=H8p9n1bVTjY

<img width="698" alt="Screenshot 2023-07-02 at 3 50 51 AM" src="https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/119984937/71b9ddd7-3556-44b8-b890-6c1f24552f6d">
<img width="1340" alt="Screenshot 2023-07-02 at 3 52 01 AM" src="https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/119984937/9c242687-2c0f-4f74-8919-d11a12da2dd8">
<img width="1310" alt="Screenshot 2023-07-02 at 3 52 20 AM" src="https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/119984937/6474e229-95db-44d8-ac12-d5d81986187c">

**Comment by santhoshb-msft** [comment]
@dillondigitals recommend running the upgrade script in a new folder.

**Comment by dillondigitals** [comment]
This worked! I ran the upgrade script in a new folder and can now see my changes!

**Comment by dillondigitals** [comment]
Does this mean I need to create a new folder each time I run the upgrade script?

**Comment by dillondigitals** [comment]
<img width="1725" alt="Screenshot 2023-07-17 at 2 02 37 AM" src="https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/119984937/0556ea01-2199-44a5-833e-3b2bd58b895e">

I tried to deploy again and I got an error message no space left on device.

**Comment by dillondigitals** [comment]
I fixed the no-space issue by upgrading the service plan and removing some temporary files.
