### ISSUE TITLE
Adding Task with current time can create task in the past.

### ISSUE THREAD

**Issue by msalemcode** [Azure/Commercial-Marketplace-SaaS-Accelerator#528]
If ISV add new scheduled task and used current time, it may create task in past. 

For example: assume ISV adding task at date 2023-07-20 11:28 AM. The task will be saved at 2023-07-20 11:00 but the engine will run at 12:00pm and it will process this task as in the past and it will skip it.

Proposed solution: to make sure to record time in future even if the ISV add the time in past. Or default the datetime to currenttime + 1 hour

**Comment by santhoshb-msft** [comment]
This is fixed in above PR, hence closing
