### ISSUE TITLE
Installation script issues

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/Commercial-Marketplace-SaaS-Accelerator#547]
**Describe the bug**
Installation script to stop when app reg secret doesn't get created.

**To Reproduce**
1. Run the installation
2. Have a scenario where app reg secret cannot be created
3. Error: Installation continues even if the App Reg secret is not created

**Expected behavior**
Installation should stop and print the error message. 
Or wait for direction to proceed or stop.

**Screenshots**

**Environment (please complete the following information):**
 - Are you using the CloudShell?
 - If not using the CloudShell:
    - PowerShell version
    - Modules installed
    
**Additional context**

**Comment by santhoshb-msft** [comment]
Check with @dstarr

**Comment by dstarr** [comment]
@santhoshb-msft Not sure why you tagged me for this issue.

**Comment by santhoshb-msft** [comment]
1. Check if you can create App Reg
2. Check if you are contributor if possible
3. [Check policies]

**Comment by santhoshb-msft** [comment]
Closing as duplicate to #473
