### ISSUE TITLE
Billing Details on Admin Page

### ISSUE THREAD

**Issue by code4clouds** [Azure/Commercial-Marketplace-SaaS-Accelerator#548]
**Is your feature request related to a problem? Please describe.**
There is no billing information on the subscription details

**Describe the solution you'd like**
I would like additional information about the subscription like plan term, start, end dates.

As an admin user that creates tenants for the SaaS solution
I would like to be able to see on the admin page the terms, start and end dates of the subscription,
So I don't have to customize this myself on the accelerator (out-the-box UX.

**Comment by alexdrenea** [comment]
I have heard this from one partner as well!
If everyone is ok, happy to take this on.

**Comment by santhoshb-msft** [comment]
This merge hence closing
