### ISSUE TITLE
Multiple Commercial-Marketplace-SaaS-Accelerator Deployments to Support Individual Offers?

### ISSUE THREAD

**Issue by brianmbennett** [Azure/Commercial-Marketplace-SaaS-Accelerator#550]
We successfully deployed the Commercial-Marketplace-SaaS-Accelerator in our tenant and have successfully connected an offer to the deployed Commercial-Marketplace-SaaS-Accelerator.

We have created another offer in our Marketplace and wanted to deploy another Commercial-Marketplace-SaaS-Accelerator in our tenant to support our new offering. We were able to successfully deploy another Commercial-Marketplace-SaaS-Accelerator making sure to give it a different “WebAppNamePrefix” and “ResourceGroupForDeployment”. We then updated our offer’s technical configuration to provide the new landing page URL, Connection webhook, tenant ID, and application ID.

However, when we visit our new web-based Admin site we are seeing subscriptions from our first deployment. We also are seeing new subscriptions from the second offering. 

Is this intended behavior? Or are wires getting crossed? 

Does the Commercial-Marketplace-SaaS-Accelerator show all marketplace offerings and their subscriptions regardless of where the offerings technical configuration specified?

Thank you,
-Brian

**Comment by santhoshb-msft** [comment]
Hi @brianmbennett , that is correct, and it is intended behavior. Generally, you can only have one accelerator instance and use it across all your offers in one publisher account. and you typically only need another instance when you have a secondary publisher account. But that doesn't stop you from having different accelerator instance pointing to different offers. But the side effect of it is what you mentioned above.

**Comment by santhoshb-msft** [comment]
@brianmbennett I hope the above comment answers your question. Please feel free to repoen for any followups
