### ISSUE TITLE
Bug in new PR in admin portal

### ISSUE THREAD

**Issue by kri-seculyze** [Azure/Commercial-Marketplace-SaaS-Accelerator#558]
**Describe the bug**
After the last PR there is an error in "Subscriptions" in the admin portal (i can see these fields were added in this PR "[src/DataAccess/Entities/Subscriptions.cs](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/commit/f840f3c71a9f826cd440ecb046636317404ed249#diff-292c6de60804d7e4b56df0678ecf6a22da254447cf4ad726f1b31bbaaeb7e8cc)"

Error:
"oops!
Error 500 : Invalid column name 'AmpOfferId'. Invalid column name 'EndDate'. Invalid column name 'StartDate'. Invalid column name 'Term'"
This is both on my demo and prod instance (the demo has subscriptions and the prod does not)

I might of course be doing something wrong?

**To Reproduce**
1. Deploy the newest version of the publisher portal
2. Go to 'the admin portal'
3. Click on 'Subscriptions'
4. See the error described above

**Expected behavior**
I expect to see all my different subscriptions / customers

**Screenshots**
![image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/76247856/a2cecd1a-7a62-4e1d-bb16-9e2f2eac9b98)

**Environment (please complete the following information):**
Using Azure webapp that was deployed via the script (and currently using pipelines to automate everything) cicd.yaml modified a bit

**Comment by santhoshb-msft** [comment]
Hi @kri-seculyze 
When the latest main was updated, have you performed the dB changes upgrade too? Please see here for our upgrade instructions.  
https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Installation-Instructions.md#update-to-a-newer-version-of-the-saas-accelerator

**Comment by kri-seculyze** [comment]
I was a little to fast on the trigger (i can see that the cicd.yaml which i modified does not do the migration of the new database changes). Thx :)

**Comment by rd-snow17** [comment]
We are also facing this issue. Can anyone help on how to resolve this?

**Comment by kri-seculyze** [comment]
@rd-snow17 you need to run the https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/deployment/Upgrade.ps1 script :) Its not part of the CICD pipeline at the point. However it looks like this is in the newer version: https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/.github/workflows/cicd.yml (            dotnet-ef migrations script  --output $sqlscriptPath --idempotent --context SaaSKitContext --project $dbAccessProj --startup-project $adminSiteProj)
