### ISSUE TITLE
Deployment scripts and templates for enterprise deployment scenarios

### ISSUE THREAD

**Issue by sowsan** [Azure/Commercial-Marketplace-SaaS-Accelerator#559]
**Is your feature request related to a problem? Please describe.**
Is there is a deployment script / ARM template available for the advance scenarios mentioned here? https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/README.md#additional-technical-documents

**Describe the solution you'd like**
Would be great to have deployment scripts and templates for those scenarios to meet well architected framework for these artifacts in Azure

**Comment by santhoshb-msft** [comment]
@sowsan  Currently there is no plans on this as we would like to keep it simple and yet have the adopters follow the recommendations to their need with the additional scenarios mentioned. I hope this answers the question. Please feel free to reopen if any followups.
