### ISSUE TITLE
Problem with installing of the SaaS Accelerator via the Cloud Shell

### ISSUE THREAD

**Issue by AndreasB92** [Azure/Commercial-Marketplace-SaaS-Accelerator#566]
Hello,
I have a problem with the installation of the SaaS Accelerator via the Cloud Shell. Can someone help me?
I get this in the log. Is this maybe the reason and what can I do for this?  @dstarr do you know about this? I followed exactly your video.

  🔵 SQL Server
      ➡️ Create Sql Server
(OperationTimedOut) The operation timed out and automatically rolled back. Please retry the operation.
Code: OperationTimedOut
Message: The operation timed out and automatically rolled back. Please retry the operation.
      ➡️ Add SQL Server Firewall rules
(SubscriptionDoesNotHaveServer) Subscription '3a0edf00-d22a-4d17-980f-f77dbfa99620' does not have the server 'xr-mm01-sql'. Please make sure that the subscription and server name are entered correctly. Please contact Microsoft support if further assistance is needed.
Code: SubscriptionDoesNotHaveServer
Message: Subscription '3a0edf00-d22a-4d17-980f-f77dbfa99620' does not have the server 'xr-mm01-sql'. Please make sure that the subscription and server name are entered correctly. Please contact Microsoft support if further assistance is needed.
      ➡️ Create SQL DB
(ResourceNotFound) The requested resource of type 'Microsoft.Sql/servers' with name 'xr-mm01-sql' was not found.
Code: ResourceNotFound
Message: The requested resource of type 'Microsoft.Sql/servers' with name 'xr-mm01-sql' was not found.
   🔵 KeyVault
      ➡️ Create KeyVault
(ConflictError) A vault with the same name already exists in deleted state. You need to either recover or purge existing key vault. Follow this link https://go.microsoft.com/fwlink/?linkid=2149745 for more information on soft delete.
Code: ConflictError
Message: A vault with the same name already exists in deleted state. You need to either recover or purge existing key vault. Follow this link https://go.microsoft.com/fwlink/?linkid=2149745 for more information on soft delete.
      ➡️ Add Secrets
(VaultNotFound) Azure Key Vault 'xr-mm01-kv' has been soft deleted. Operations on this vault can be performed only after recovering it. For recovery instructions see https://go.microsoft.com/fwlink/?linkid=2125182
Code: VaultNotFound
Message: Azure Key Vault 'xr-mm01-kv' has been soft deleted. Operations on this vault can be performed only after recovering it. For recovery instructions see https://go.microsoft.com/fwlink/?linkid=2125182
(VaultNotFound) Azure Key Vault 'xr-mm01-kv' has been soft deleted. Operations on this vault can be performed only after recovering it. For recovery instructions see https://go.microsoft.com/fwlink/?linkid=2125182
Code: VaultNotFound
Message: Azure Key Vault 'xr-mm01-kv' has been soft deleted. Operations on this vault can be performed only after recovering it. For recovery instructions see https://go.microsoft.com/fwlink/?linkid=2125182
   🔵 App Service Plan
      ➡️ Create App Service Plan
{

**Comment by AndreasB92** [comment]
Hello, I dont know why but the installation worked now. @santhoshb-msft Can you tell me how I can access the admin publisher portal? It is never mentioned in the videos and just shown.

**Comment by santhoshb-msft** [comment]
@AndreasB92 please review the services deployed during the installation and there should should be a couple of appservices. One is your customer app and the other one should be the admin portal. I hope this helps!
