### ISSUE TITLE
Validate the uniqueness of the resource prefix. 

### ISSUE THREAD

**Issue by tfsjohan** [Azure/Commercial-Marketplace-SaaS-Accelerator#568]
**Is your feature request related to a problem? Please describe.**
When running the install script the web site prefix must globally unique. This is documented, but easy to miss. If you choose a prefix that is not available, you will get an error, but the error will be hidden in the console output and you'll only discover it after the script has run, which for me takes about 10 minutes. 

**Describe the solution you'd like**
I would like that the uniqueness of the prefix name is validated before the deployment of resources are begun. I guess it's the keyvault that needs to be globally unique, so maybe we can use the CLI to check if the name is available. 

**Describe alternatives you've considered**
An alternativ would be to exit the script directly after the keyvault creation fails and be very clear in the output why it failed.

Maybe it should even be optional to enter your own prefix, and if missing, create a hash from a guid that will be unique.

**Comment by tfsjohan** [comment]
Maybe something like this could do the trick. 

```PS1
if (-not (Test-AzKeyVaultNameAvailability -Name "desired-keyvault-name")) {
    throw "KeyVault name is not available"
}

```

**Comment by santhoshb-msft** [comment]
closing this based on above merge.
