### ISSUE TITLE
User can schedule task even if scheduler is disabled

### ISSUE THREAD

**Issue by msalemcode** [Azure/Commercial-Marketplace-SaaS-Accelerator#569]
User can access Add new Task form even if scheduler is disabled.

**To Reproduce**
1. Deploy Accelerator without meter support.'
2. Click on subscription -> manage usage
3. Click schedule task

**Expected behavior**
Schedule task button should be hidden in case of scheduler disabled.

**Comment by santhoshb-msft** [comment]
This should now be fixed in #626
