### ISSUE TITLE
Installer stops when old keyvault is present

### ISSUE THREAD

**Issue by dstarr** [Azure/Commercial-Marketplace-SaaS-Accelerator#572]
**Is your feature request related to a problem? Please describe.**
Many deployments are failing for partners who do not know to purge the old KV in between install runs.

**Describe the solution you'd like**
The install should check for existing key vaults that match the current install parameters. If an existing KV is present then provide a message that indicates the presence of the KV and exit the installer.

**Notes**

1. Do this check before any other resources are deployed.
2. The exit message should indicate what is wrong (existing KV exists)
3. The exit message can include a link to the MS doc on purging a KV

**Comment by santhoshb-msft** [comment]
Print the message and abort the installation

**Comment by pkdhingra** [comment]
I am getting this erroe - Throw "🛑 KeyVault name only allows alphanumeric and hyphens.  i have not specific keyvault and it is not even asking
