### ISSUE TITLE
Missing views and controllers

### ISSUE THREAD

**Issue by jeffw-wherethebitsroam** [Azure/Commercial-Marketplace-SaaS-Accelerator#584]
**Describe the bug**
References to missing views and controllers

**To Reproduce**
Checkout and build

**Expected behavior**
Expected that all referenced views and controllers would exist.

e.g.
AdminSite AccountController SignedOut
AdminSite ApplicationConfig Index.cshtml -> references missing FileUpload controller
AdminSite HomeController ActivateSubscription
AdminSite HomeController Privacy
AdminSite SchedulerController GetSubscriptionData -> passes a string as a model to Error expecting an Exception
CustomerSite AccountController SignedOut

**Environment (please complete the following information):**
Rider on macOS

**Comment by santhoshb-msft** [comment]
@jeffw-wherethebitsroam some of these controllers are called and redirected to other views. I dont believe this is an issue, please reopen with further comments if needed. closing for now.
