### ISSUE TITLE
Could not find file "script.sql"

### ISSUE THREAD

**Issue by FilibertoNencioni** [Azure/Commercial-Marketplace-SaaS-Accelerator#590]
Hi, I'm trying to start the deployment script (Deploy.ps1) directly from the PowerShell in Azure Portal, but every time I receive the same error even if it states that the build succeeded.

**Deploy**
```powershell
dotnet tool install --global dotnet-ef; `
git clone https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator.git -b 7.4.0 --depth 1; `
cd ./Commercial-Marketplace-SaaS-Accelerator/deployment; `
.\Deploy.ps1 `
-WebAppNamePrefix "xxxxx" `
-ResourceGroupForDeployment "xxxxx" `
-PublisherAdminUsers "xxxxx" `
-Location "West Europe" `
-TenantID "xxxxx" `
-AzureSubscriptionID "xxxxx"
``` 

**Error**
![MicrosoftTeams-image](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/29194262/458954b3-444c-4155-b411-890b5aa71ebc)

**Environment:**
 - Cloud Shell (from Azure portal)
 - DotNet-ef 7.0.31

**Comment by santhoshb-msft** [comment]
Hi @FilibertoNencioni please use the complete command from the [installation instructions](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/blob/main/docs/Installation-Instructions.md#basic-installation-script), which should add dotnet 6 installation.

In the next release we will have our install script check for dotnet 6., please see here for more info #583 before running the script.  Closing this for now, please feel free to reopen on any additional questions.
