### ISSUE TITLE
Invalid object name 'dbo.SchedulerFrequency' when upgrading from Version 5

### ISSUE THREAD

**Issue by sm-jchalmers** [Azure/Commercial-Marketplace-SaaS-Accelerator#594]
We are trying to upgrade from Version 5 to the current version and are getting the following error:

`Invoke-Sqlcmd: /home/hidden/Commercial-Marketplace-SaaS-Accelerator/deployment/Upgrade.ps1:80
Line |
  80 |  Invoke-Sqlcmd -inputFile script.sql -ServerInstance $Server -database …
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | Invalid object name 'dbo.SchedulerFrequency'.   Msg 208, Level 16, State 1, Procedure , Line 5.
PS /home/hidden/Commercial-Marketplace-SaaS-Accelerator/deployment> `

Is anyone able to help with this?

**Comment by santhoshb-msft** [comment]
I think we worked on this and got a new version instaled. Please feel free to reopen this if needed. @sm-jchalmers

**Comment by sm-jchalmers** [comment]
Hi Santosh,You are correct. Thank you,Jeff ChalmersVP Finance and OperationsSight Machine408-833-5329On Nov 28, 2023, at 4:08 PM, SANTHOSH B ***@***.***> wrote:﻿
I think we worked on this and got a new version instaled. Please feel free to reopen this if needed. @sm-jchalmers

**Comment by santhoshb-msft** [comment]
Thank you, Jeff, for confirming!
