### ISSUE TITLE
The admin portal is not opening. showing as access denied

### ISSUE THREAD

**Issue by NareshkumarBT** [Azure/Commercial-Marketplace-SaaS-Accelerator#595]
**Admin Portal is access denied**
I clone the source code and launched in visual studio. The admin portal portal page is showing as access denied..

**Comment by santhoshb-msft** [comment]
Hi @NareshkumarBT , please add yourself as KnownUsers in the app service config or add your email to the database.

**Comment by NareshkumarBT** [comment]
Thankyou. I added my user in Knownusers and could able to login?

**Comment by Chirag-CG** [comment]
Hi @NareshkumarBT , I am also facing the same issue even though I have added my email ID in the config as KnownUsers
![Screenshot from 2023-12-21 16-06-34](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/126187841/94673d51-4b5c-468c-b69f-fe49d6cec20a)
Please let me know how you were able to resolve this issue.
