### ISSUE TITLE
WebNotificationUrl Admin Setting Missing

### ISSUE THREAD

**Issue by adrian-spear** [Azure/Commercial-Marketplace-SaaS-Accelerator#610]
WebNotificationUrl admin setting is missing from the app settings config in Admin app.
As per this video: https://www.youtube.com/watch?v=A7TKSE08dAY&t=277s at 04:37.00 - I am attempting to set up external notification feature.
I installed Accelerator from Azure Marketplace but have published from the latest main branch to no avail.

**To Reproduce**
1. Go to Admin Settings
2. WebNotificationUrl setting is missing

**Expected behavior**
Expected 'WebNotificationUrl' setting to be available.

**Screenshots**
None.

**Environment (please complete the following information):**
Deployed to App Service (Windows) as per instruction provided in your video how to install from Azure Marketplace.

**Comment by santhoshb-msft** [comment]
@adrian-spear which version are you using? latest 7.4.0? in that case then should see the setting coming in from the database,

**Comment by adrian-spear** [comment]
Hi,

The latest migration in the source code is ‘20230912052848_SubscriptionDetails_v740’ so I’m going to say ‘Yes’ to 7.4.0. The code for both admin and customer portals has been deployed using Visual Studio Publish.

The migrations history in the database is still showing ‘20221118211554_Baseline_v6’ so my database requires the migrations.

Please advise how to apply the migrations to the production database?

Thanks very much for your attention on this – it is much appreciated.

Best regards,
Adrian



Adrian Spear
Technical Director

[cid:li-logo-codetwo-email-s_1e9e43da-653e-4bd9-b9f6-44776db87678.png]<https://www.linkedin.com/in/adrianspear> [cid:fs_logo_sml_r_10348fea_f68702a0-1fe9-4c67-b668-7f0690c7ccf8.png] <https://fidrasoft.com/>

***@***.******@***.***> | https://teamfolio.co.uk
[cid:emailsignature_banner_s_eab6ce00-226a-4e79-808a-19abb64346e8.png] <https://teamfolio.co.uk>
NOTE: This message may contain confidential and/or legally privileged information. If it has been sent to you in error, please reply immediately to advise the sender of the error and then destroy this message, any copies of this message and any printout of this message. If you are not the intended recipient of the message, any unauthorized dissemination, distribution or copying of the material in this message and any attachments to the message, is strictly forbidden.

**Comment by adrian-spear** [comment]
Hi,

Thanks – no custom app changes and not planning on any at this time so I think we’re good.

I had found the powershell update info you recommend but wasn’t sure if this would apply the database changes – you indicate it will so I’ll go down that route.

We have not gone live with any marketplace offers yet so there’s nothing to lose if we have to tear down the accelerator and start again but rest assured a staging environment will be established before any offer go-lives take place &#128522;

All the best,



Adrian Spear
Technical Director

[cid:li-logo-codetwo-email-s_1e9e43da-653e-4bd9-b9f6-44776db87678.png]<https://www.linkedin.com/in/adrianspear> [cid:fs_logo_sml_r_10348fea_f68702a0-1fe9-4c67-b668-7f0690c7ccf8.png] <https://fidrasoft.com/>

***@***.******@***.***> | https://teamfolio.co.uk
[cid:emailsignature_banner_s_eab6ce00-226a-4e79-808a-19abb64346e8.png] <https://teamfolio.co.uk>
NOTE: This message may contain confidential and/or legally privileged information. If it has been sent to you in error, please reply immediately to advise the sender of the error and then destroy this message, any copies of this message and any printout of this message. If you are not the intended recipient of the message, any unauthorized dissemination, distribution or copying of the material in this message and any attachments to the message, is strictly forbidden.

**Comment by santhoshb-msft** [comment]
Sounds good! Closing this for now. Please feel free to reopen or open a new issue as needed.
