### ISSUE TITLE
Setup Webhook

### ISSUE THREAD

**Issue by NareshkumarBT** [Azure/Commercial-Marketplace-SaaS-Accelerator#618]
I went through the webhook implementation video(https://www.youtube.com/watch?v=higEi441t1Q).
An azure function is created and getting the JSON response.
Using the JSON response do we need to save the subscription details in Subscriptions table ?

Is there any other way to implement?
Could someone please give detailed explanation on setting up Webhook?

Or 

Is that enough if we insert a record in **ApplicationConfiguration** table with name as **WebNotificationUrl** and value as webhook url ?

**Comment by NareshkumarBT** [comment]
any update on this please?

**Comment by NareshkumarBT** [comment]
Hi @santhoshb-msft 

Could you please help me here?

Im getting internal server error after adding the webhook url in applicationconfiguration table.

**Comment by santhoshb-msft** [comment]
@NareshkumarBT i think there are few questions here. Implementing external web notification is an optional feature to connect to your other systems if needed. Can you explain more when you say you are getting an error. You mean after adding and removing it, you are getting an error?

**Comment by NareshkumarBT** [comment]
I inserted a record in ApplicationConfiguration table with name as WebNotificationUrl and value as webhook url(https://demo-saas-portal.azurewebsites.net/api/AzureWebhook) as part of webhook implementation.

From market place i subscribed and Configuring the Saas offer.
When i click on subscribe, im getting 500 error(Refer 500_Error.png), but after navigating to Subscriptions page i could see the subscription details(Subscription.png)
![500_Error](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/151021516/2a7ea78f-b720-417f-bbeb-bae38796bcbc)
![Subscription](https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/151021516/1e98cbac-3571-4c71-84aa-61b9c29caf8b)

**Comment by NareshkumarBT** [comment]
Hi @santhoshb-msft 

I noticed below points after publishing the customer portal.
1. When we configure the Saas Offer from marketplace, it is redirecting to landing page with Subscription details and Subscribe button.
2. When we click on Subscribe button, it is taking more time(app 40 secs) and navigating to process page.
3. I see in the Subscribe click, internally calling webhook post method and it is taking time.

Please suggest me, how to avoid the time and please let me know what actions to be taken.

Thanks in advance.

**Comment by santhoshb-msft** [comment]
@NareshkumarBT can you try removing your web external link if you re not using it?

**Comment by NareshkumarBT** [comment]
@santhoshb-msft 
I'm using that webnotification link(https://demo-saas-portal.azurewebsites.net/api/AzureWebhook) to get webhook notifications.
I added the url in ApplicationConfiguration table

**Comment by santhoshb-msft** [comment]
@NareshkumarBT  no thats not correct. You should use this link in your offer technical configuration. 
External Web Notification feature in the App Config is a completely different feature used for different purpose. For more information on what an External Web Notification feature is please review here. https://microsoft.github.io/Mastering-the-Marketplace/saas-accelerator/#using-the-external-notification-feature

**Comment by NareshkumarBT** [comment]
@santhoshb-msft 

When customer click on subscribe, using external web notification url the action is taken to external endpoint to take actions accordingly.
Using webhook, if the customer is already activated Saas offer and if there is any change plan or unsubscribe the action is taken to external endpoint.

My question here is, if i remove the web notification url how the webhook will hit the external endpoint and receive notification?
What change do we need to do for webhook notification ?

**Comment by santhoshb-msft** [comment]
@NareshkumarBT - Webhhook is different to ExternalWebNotification.

Webhook - is already part of the Accelerator customer site app, which you will use in your offer technical configuration, and you will receive notification from Marketplace on any customer changes are described [here](https://learn.microsoft.com/en-us/partner-center/marketplace/partner-center-portal/pc-saas-fulfillment-webhook).


ExternalWebNotificaion is a different, additional, optional feature if you would like to further forward the above received notifications to your other systems.

To start with, does this distinction help?

**Comment by santhoshb-msft** [comment]
@NareshkumarBT hope the above clarifies, if not please feel free to reopen with further questions. closing this for now.

**Comment by BayScallop** [comment]
I don't know if you can help and I see this is closed, but I am having an issue where the (Azure Marketplace) WebHook I created never receives a notification from the Azure Marketplace. I have followed the patters in the docs and can hit the webhook API's with Postman and monitor the WebHook in the Azure Logs. The WebHook is an Azure SaaS service. I have opened a case with Microsoft Partner Center but they cannot seem to provide any answers. This is the last item I need to complete before submitting my offer for certification. I can provision and activate a test subscription from the Landing Page but when I make changes in the Azure SaaS Dashboard, no webhook call occurs. I figure it is either: 1) blocked at the network level (don't think so as it is public); 2) Saas service is not in a correct state to send WebHook messages (I can activate a test subscription); 3) Issue with endpoint (I have tired several as the docs and online postings have several variations)
