### ISSUE TITLE
Deprecation of product-ingestion.azureedge.net - is it used in the accelerator?

### ISSUE THREAD

**Issue by Narunas-K** [Azure/Commercial-Marketplace-SaaS-Accelerator#622]
Hello,

I am using Commercial Marketpalce SaaS Accelerator and have received an email from "Microsoft Partner Center" stating that `product-ingestion.azureedge.net` endpoint will be deprecated on March 5, 2024.

"On March 5, 2024 all [product-ingestion.azureedge.net](http://product-ingestion.azureedge.net/) schema endpoints will be replaced with [schema.mp.microsoft.com](http://schema.mp.microsoft.com/), and any requests to [product-ingestion.azureedge.net](http://product-ingestion.azureedge.net/) will begin to timeout. 

If you are referencing [product-ingestion.azureedge.net](http://product-ingestion.azureedge.net/) in your codebase, please update to [schema.mp.microsoft.com](http://schema.mp.microsoft.com/) before March 5, 2024."

Could you confirm that this endpoint is used in Commercial Marketpalce SaaS Accelerator?
If yes, which version of the deployment should I use to avoid any outages past March 5th?

**Comment by santhoshb-msft** [comment]
Hi @Narunas-K I don't believe we use the product injection endpoint product-ingestion.azureedge.net in the SaaS Accelerator. All we use is the Marketplace Apis. What you have received could be Partner center specific and I recommend raising a support ticket within our partner center to get more information on the same. Please feel free to reopen with more questions if needed
