### ISSUE TITLE
Help! SaaS Accelerator Issue: 500 Error on Admin Site

### ISSUE THREAD

**Issue by mattsoseman** [Azure/Commercial-Marketplace-SaaS-Accelerator#654]
After deploying your Marketplace SaaS Accelerator, I changed settings on the Admin site for sending email notifications and added SMTP configuration. However now I'm getting a 500 error message when loading the application config page on the admin site (screenshot below). I thought maybe I fat fingered something, so I connected to the SQL table and reverted the settings in those rows back to NULL and restarted the App Service, but same results.

Any ideas? How can I go about troubleshooting this? Thanks in advance!
<img width="960" alt="screenshot" src="https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/136049104/0465ac9f-0ee3-48aa-ba99-f7be40972a94">

**Comment by santhoshb-msft** [comment]
Hi @mattsoseman - can you try setting them to empty strings from db. This issue is fixed and will be available in the new release of SaaS accelerator. #647#633

**Comment by mattsoseman** [comment]
> Hi @mattsoseman - can you try setting them to empty strings from db. This issue is fixed and will be available in the new release of SaaS accelerator. #647 #633

That fixed it, thanks so much Santhosh!

**Comment by santhoshb-msft** [comment]
Glad its fixed, @mattsoseman. Closing this for now, please let us know if you have any other questions.
