### ISSUE TITLE
Invalid font path in error CSS files

### ISSUE THREAD

**Issue by PhilMar-StratusInnovations** [Azure/Commercial-Marketplace-SaaS-Accelerator#669]
Whenever an error occurs, the error page attempts to load a font from an incorrect path.

Under both the Admin and Customer sites, wwwroot\css\Error\font-awesome-min.css has several sources like the following:

src:url('../fonts/fontawesome-webfont.eot?v=4.7.0')

However, there's no ../fonts directory.  There is, however, a '../font-awesome/fonts directory.

Should, ../fonts/ be updated to ../font-awesome/fonts/ ?

I did this with my company's installation of the accelerator, and it seems to work.

**Comment by neelavarshad** [comment]
Resolved in commit a39e425f9aecaba28648c2335dae11a6a2efc9cb
