### ISSUE TITLE
App Service plan BadGateway

### ISSUE THREAD

**Issue by Tom-H2oThermo** [Azure/Commercial-Marketplace-SaaS-Accelerator#708]
When I follow the instructions here:
https://www.youtube.com/watch?v=B5l5p9LvDSU
At the final step when I hit review and create, I'm getting an error,BadGateway.  It just keeps showing "Deployment is in progress"

<img width="518" alt="image" src="https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/25697066/0d0fadf6-a24a-4bcf-adb6-446e5afc1049">

<img width="497" alt="image" src="https://github.com/Azure/Commercial-Marketplace-SaaS-Accelerator/assets/25697066/d543a10b-e48b-4ca4-945c-840c7c369d51">

I'm using Windows 11.

Any suggestions?

**Comment by santhoshb-msft** [comment]
@Tom-H2oThermo I believe this might be related to the user permissions for creating app service plan. Please contact your Azure subscription owner for more help on this.

**Comment by Tom-H2oThermo** [comment]
I figured out the problem.  I had to go to my app registration for the Single Tenant and Multi Tenant apps, which are pre-requisites for deploying the SaaS Accelerator.  Then under Manage/Owners I had to make myself an Owner.

**Comment by Tom-H2oThermo** [comment]
I figured out the problem.  I had to go into my Single Tenant and Multi Tenant app registrations which are pre-requisites for deploying the SaaS Accelerator.  Then under Manage/Owners I had to make myself an owner.  Problem solved.
