### ISSUE TITLE
[QUESTION]: Redirect to product website after 'Subscribe' on Accelerator Landing Page

### ISSUE THREAD

**Issue by stasdykyi** [Azure/Commercial-Marketplace-SaaS-Accelerator#741]
We currently have our product listed in the Marketplace with a 'Contact Me' integration, and we want to transition to a transactable offer.

I reviewed the documentation and videos on integrating the Accelerator Landing Page, but I couldn't find any information on how to redirect the user (or at least show them a link to our website's sign-up page) after they click the 'Subscribe' button.

We can create an account for the user when we receive the initial webhook from Accelerator. However, it's a bit strange that a user logs in, proceeds with their subscription via the 'Subscribe' button, and then has no way to access the site where they just bought the subscription.

**Is it possible to redirect the user to our product website after they click the 'Subscribe' button?** We want to ensure that the user creates an account on our product site, receives all the features included in their subscription, and activates the subscription at that moment.

Or am I missing something about how the flow is supposed to work? Thank you in advance!

**Comment by santhoshb-msft** [comment]
@stasdykyi when the users subscribe, they go to the landing page which in this case is SaaS accelerator landing page. There are few options on how you can get that customer to your product page
1. Implement your own landing page with the desired logic and use it in the saas offer
2. add your product link in the app settings and that should give the customers a link to go to product page
3. Use the external webhook feature or email to receive events and follow up with the customer on the next steps

**Comment by stasdykyi** [comment]
@santhoshb-msft how also could be handled case when several people under the same tenant "share" or have access to the same subscription?
