### ISSUE TITLE
Unable to update the Microsoft Entra Client Secret for an existing SaaS Accelerator installation.  

### ISSUE THREAD

**Issue by labtest2023** [Azure/Commercial-Marketplace-SaaS-Accelerator#769]
I have installed the SaaS Accelerator several months ago, and now it is time to update the Client Secret for my Enterprise App Registrations for my Single Tenant, and Multi-Tenant App Registrations within Microsoft Entra. I do not see a method to update the Microsoft Entra Enterprise App Registration "Client Secret" for an existing SaaS Accelerator installation. Please let me know, is it possible to update the Client Secret for an Enterprise App Registration, and for the SaaS Accelerator to recognize the new client secret. I am not simply referring to the method to update the Client Secret in Microsoft Entra, but I am specifically referring to the method to changing the configuration of an existing SaaS Accelerator installation so that it acknowledges, and utilizes the newly replaced "Client Secret" from Microsoft Entra. This is time sensitive, please advise.

**Comment by fthorntonai** [comment]
https://partner.microsoft.com/en-us/training/assets/detail/replacing-application-secrets-for-the-saas-accelerator-mp4

**Comment by labtest2023** [comment]
Thank you



[[NAME]]<https://www.bqignite.com/api/SignatureMetadata/GetRedirect?Guid=3f2fa97bdfec4f3d83316737e2dd2a38>

________________________________
