### ISSUE TITLE
AppVersionService breaks build due to missed reference updates

### ISSUE THREAD

**Issue by mattwise-42** [Azure/Commercial-Marketplace-SaaS-Accelerator#770]
**Describe the bug**
PR #766 changed AppVersionService and it expect a Version object but the code still passes a FileVersionInfo object in parts of the code. Currently the solution does not build successfully.

**To Reproduce**
1. run 'dotnet build'

**Expected behavior**
Build output:

> /workspaces/Commercial-Marketplace-SaaS-Accelerator/src/MeteredTriggerJob/Program.cs(59,69): error CS1503: Argument 1: cannot convert from 'System.Diagnostics.FileVersionInfo' to 'System.Version' [/workspaces/Commercial-Marketplace-SaaS-Accelerator/src/MeteredTriggerJob/MeteredTriggerJob.csproj]

**Environment (please complete the following information):**
 - .NET 8 Dev Container

**Comment by mdsabbir28july** [comment]
- ``

**Comment by fthorntonai** [comment]
Resolved with the breakfix for "MeteredTriggerJob failing due to Unhandled exception #772"
