### ISSUE TITLE
Instructions on using KeyVault to save and load configuration from KeyVault 

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/Commercial-Marketplace-SaaS-Accelerator#88]
**Is your feature request related to a problem? Please describe.**
Not a problem but just some information using KeyVault is a good to have

**Describe the solution you'd like**
Created a PR updating that information in Installation readme PR #87 

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by alexdrenea** [comment]
#156 adds a new deployment script based on AZ Cli that adds keyvault to the solution.

This issue can be closed!
