### ISSUE TITLE
Instructions conflicting with behavior for IsAutomaticProvisioningSupported

### ISSUE THREAD

**Issue by santhoshb-msft** [Azure/Commercial-Marketplace-SaaS-Accelerator#98]
**Describe the bug**
Instructions are conflicting the behavior, see screen shots below
Instructions say 
_**If the value is True, the options - Change Plan & Unsubscribe are not available to the customer. Clicking **Activate** button on the landing page would place the subscription in PendingActivation status and doesn't activate the subscription yet. Publisher has the option to activate the subscription, change plan and unsubscribe.**_ 

**_If the value is False, customer can activate, change plan and unsubscribe with any intervention required from the publisher._**

But the behavior is opposite

**To Reproduce**
1. Go to database and update IsAutomaticProvisioningSupported to false
2. See the customer app only shows ActivityLog
3. update IsAutomaticProvisioningSupported to True
4. Customer app provides option to ChangePlan and Unsubscribe

**Expected behavior**
_**If the value is False, the options - Change Plan & Unsubscribe are not available to the customer. Clicking **Activate** button on the landing page would place the subscription in PendingActivation status and doesn't activate the subscription yet. Publisher has the option to activate the subscription, change plan and unsubscribe.**_ 

**_If the value is True, customer can activate, change plan and unsubscribe with any intervention required from the publisher._**

**Screenshots**
![image](https://user-images.githubusercontent.com/63607175/88239777-2f2eff00-cc3a-11ea-8463-feb5db296072.png)

![image](https://user-images.githubusercontent.com/63607175/88239738-1292c700-cc3a-11ea-99e0-65312ca2da75.png)

![image](https://user-images.githubusercontent.com/63607175/88239757-1d4d5c00-cc3a-11ea-9e3f-679037a5775f.png)

![image](https://user-images.githubusercontent.com/63607175/88239766-250d0080-cc3a-11ea-80a1-e356976a1e42.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dev-kiranbanda** [comment]
Hi Santosh,

I shall take a look at this and update the implementation / document with relevant changes.

Regards,
Kiran Banda

**Comment by santhoshb-msft** [comment]
@dev-kiranbanda 
Already raised a PR for this #99 , if it helps!

**Comment by santhoshb-msft** [comment]
Closing as PR merged.
